In [2]:
import pandas as pd
import os
import numpy as np

In [3]:
# Data_Quality_Indicator = 'C:/Users/jkumava/Downloads/Language_Practice/Python/Playground/xdi_input_1007896757/1007896757/20240304_RCP26_ID_1007896757/ID_1007896757_Data Quality Indicator.csv'

In [4]:
Data_Quality_Indicator = 'C:/Users/jkumava/Downloads/PCRM/1008128171/RCP_26/ID_1008128171__Failure Probability.csv'

In [171]:
base_path = os.path.dirname(Data_Quality_Indicator)

base_path

'C:/Users/jkumava/Downloads/PCRM/1008128171/RCP_26'

In [6]:
REFERENCE_YEAR = 2021
import_years = (2030,2050,2100,2045,2035,2040,2025,2022,2027,2023,2028)

## Failure Probability

In [7]:
comp_id = 'ID_1008128171'
failure_p = base_path+f'/{comp_id}_Failure Probability.csv'

In [8]:
failure_probability_df = pd.read_csv(failure_p)
failure_probability_df['CompanyID'] = failure_probability_df['CompanyID'].str.replace('ID_','')
failure_probability_df = failure_probability_df[failure_probability_df['Year'].isin(import_years)].reset_index(drop=True)
failure_probability_df.head()

  Scenario   CompanyID         CompanyName Country  Year        FP
0   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2022  0.992893
1   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2023  0.992893
2   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2025  0.992893
3   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2027  0.992893
4   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2028  0.992893

In [9]:
Hazard_Breakdown_df = pd.read_csv(base_path+f'/{comp_id}_Hazard Breakdown.csv')

Hazard_Breakdown_df['CompanyID'] = Hazard_Breakdown_df['CompanyID'].str.replace('ID_','')
Hazard_Breakdown_df = Hazard_Breakdown_df[Hazard_Breakdown_df['Year'].isin(import_years)].reset_index(drop=True)
Hazard_Breakdown_df.head()

,Scenario,CompanyID,CompanyName,Country,Year,Hazard,HazMVAR,HazFP,HazPL
0,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Coastal Inundation,0.000000,0.000000,0.000000e+00
1,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Cyclone Wind,0.000003,0.000013,5.000000e-07
2,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Extreme Heat,0.000000,0.992890,2.720250e-03
3,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Extreme Wind,0.000047,0.000414,3.400000e-06
4,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Forest Fire,0.000000,0.000000,0.000000e+00

In [10]:
Hazard_computation_df = pd.read_csv(base_path+f'/{comp_id}_Hazard Computation.csv')

Hazard_computation_df['CompanyID'] = Hazard_computation_df['CompanyID'].str.replace('ID_','')
Hazard_computation_df = Hazard_computation_df[Hazard_computation_df['Year'].isin(import_years)].reset_index(drop=True)
Hazard_computation_df.head()

,Scenario,CompanyID,CompanyName,Country,Year,Hazard,SumHazMVAR,HazMVAR_Flag,SumHazFP,HazFP_Flag,SumHazPL
0,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Coastal Inundation,0.000000,0,0.000000,0,0.000000e+00
1,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Cyclone Wind,0.000003,0,0.000013,0,5.000000e-07
2,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Extreme Heat,0.000000,0,0.992890,1,2.720250e-03
3,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Extreme Wind,0.000047,0,0.000414,0,3.400000e-06
4,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Forest Fire,0.000000,0,0.000000,0,0.000000e+00

In [11]:
Productivity_Loss_df = pd.read_csv(base_path + f'/{comp_id}_Productivity Loss.csv')
Productivity_Loss_df['CompanyID'] = Productivity_Loss_df['CompanyID'].str.replace('ID_','')
Productivity_Loss_df = Productivity_Loss_df[Productivity_Loss_df['Year'].isin(import_years)].reset_index(drop=True)
Productivity_Loss_df.head()

  Scenario   CompanyID         CompanyName Country  Year        PL
0   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2022  0.002724
1   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2023  0.002724
2   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2025  0.002724
3   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2027  0.002724
4   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2028  0.002724

### Calculation of Counts Table

In [12]:
Risk_bands_df = pd.read_csv(base_path+f'/{comp_id}_Risk Bands.csv')
Risk_bands_df['CompanyID'] = Risk_bands_df['CompanyID'].str.replace('ID_','')
Risk_bands_df = Risk_bands_df[Risk_bands_df['Year'].isin(import_years)].reset_index(drop=True)
counts_df = Risk_bands_df.rename(columns={'HRP#': 'count_uninsured','MRP#' : 'count_0_2_pct', 'LRP#' : 'count_0_5_pct'})
counts_df = counts_df[['Scenario', 'CompanyID', 'CompanyName', 'Country', 'Year',
       'count_uninsured','count_0_2_pct', 'count_0_5_pct']]
counts_df

,Scenario,CompanyID,CompanyName,Country,Year,count_uninsured,count_0_2_pct,count_0_5_pct
0,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,0,0,1
1,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2023,0,0,1
2,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2025,0,0,1
3,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2027,0,0,1
4,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2028,0,0,1
...,...,...,...,...,...,...,...,...
479,RCP2.6,1008128171,Barrick Gold Corp.,ZMB,2035,0,0,1
480,RCP2.6,1008128171,Barrick Gold Corp.,ZMB,2040,0,0,1
481,RCP2.6,1008128171,Barrick Gold Corp.,ZMB,2045,0,0,1
482,RCP2.6,1008128171,Barrick Gold Corp.,ZMB,2050,0,0,1
483,RCP2.6,1008128171,Barrick Gold Corp.,ZMB,2100,0,0,1

In [13]:
tzero_df = pd.read_csv(base_path+f'/{comp_id}_Company Info.csv')
tzero_df['CompanyID'] = tzero_df['CompanyID'].str.replace('ID_','')
# Company_Info_df = Company_Info_df[Company_Info_df['Year'].isin(import_years)].reset_index(drop=True)
tzero_df.head()

    CompanyID         CompanyName Country  Count  ReplacementCost   Turnover
0  1008128171  Barrick Gold Corp.     ARE      1        1000000.0    2000000
1  1008128171  Barrick Gold Corp.     ARG      5        5000000.0   10000000
2  1008128171  Barrick Gold Corp.     AUS    107      107000000.0  214000000
3  1008128171  Barrick Gold Corp.     BEL      1        1000000.0    2000000
4  1008128171  Barrick Gold Corp.     BFA      2        2000000.0    4000000

In [14]:
Computation_df = pd.read_csv(base_path+f'/{comp_id}_Computation.csv')
Computation_df['CompanyID'] = Computation_df['CompanyID'].str.replace('ID_','')
Computation_df = Computation_df[Computation_df['Year'].isin(import_years)].reset_index(drop=True)
Computation_df.head()

,Scenario,CompanyID,CompanyName,Country,Year,SumMVAR,SumFP,SumPL
0,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,0.000049,0.992893,0.002724
1,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2023,0.000049,0.992893,0.002724
2,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2025,0.000050,0.992893,0.002724
3,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2027,0.000050,0.992893,0.002724
4,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2028,0.000051,0.992893,0.002724

In [15]:
fmi_df = pd.read_csv(base_path+f'/{comp_id}_First Mile Indicator.csv')
fmi_df['CompanyID'] = fmi_df['CompanyID'].str.replace('ID_','').astype(int)
fmi_df['FMI'] = pd.to_numeric(fmi_df['FMI'], errors='coerce')

fmi_df = fmi_df[fmi_df['Year'].isin(import_years)].reset_index(drop=True)
fmi_df.head()

  Scenario   CompanyID         CompanyName Country  Year       FMI
0   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2022  0.001993
1   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2023  0.002134
2   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2025  0.002413
3   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2027  0.002793
4   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2028  0.002981

In [16]:
rei_df = pd.read_csv(base_path+f'/{comp_id}_Regional Economic.csv')
rei_df['CompanyID'] = rei_df['CompanyID'].str.replace('ID_','')
rei_df = rei_df[rei_df['Year'].isin(import_years)].reset_index(drop=True)
rei_df.head()

  Scenario   CompanyID         CompanyName Country  Year       REI
0   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2022  0.005404
1   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2023  0.005404
2   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2025  0.005404
3   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2027  0.005404
4   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2028  0.005404

In [17]:
sbscp_df = pd.read_csv(base_path+f'/{comp_id}_Sector-Based Supply-Chain Proxy.csv')
sbscp_df['CompanyID'] = sbscp_df['CompanyID'].str.replace('ID_','')
sbscp_df = sbscp_df[sbscp_df['Year'].isin(import_years)].reset_index(drop=True)
sbscp_df.head()

  Scenario   CompanyID         CompanyName Country  Year       SSP
0   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2022  0.001530
1   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2023  0.001572
2   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2025  0.001629
3   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2027  0.001703
4   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2028  0.001765

In [18]:
var_df = pd.read_csv(base_path+f'/{comp_id}_Value-At-Risk.csv')
var_df['CompanyID'] = var_df['CompanyID'].str.replace('ID_','')
var_df = var_df[var_df['Year'].isin(import_years)].reset_index(drop=True)
var_df.head()

  Scenario   CompanyID         CompanyName Country  Year      MVAR
0   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2022  0.000049
1   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2023  0.000049
2   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2025  0.000050
3   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2027  0.000050
4   RCP2.6  1008128171  Barrick Gold Corp.     ARE  2028  0.000051

In [19]:
# xdi_data = fmi_df.merge(rei_df,on=[ 'CompanyID','Scenario', 'CompanyName', 'Country','Year'],how='outer')
# xdi_data = xdi_data[xdi_data['Year'].isin(import_years)].reset_index(drop=True)

## Hazard Rate and Hazard Risk

In [20]:
Hazard_Breakdown_df['Hazard'] = Hazard_Breakdown_df['Hazard'].apply(
    lambda x: 'Flooding' if x in ['Riverine Flooding', 'Surface Water Flooding'] else x
)
Hazard_Breakdown_df.head(10)

,Scenario,CompanyID,CompanyName,Country,Year,Hazard,HazMVAR,HazFP,HazPL
0,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Coastal Inundation,0.000000,0.000000,0.000000e+00
1,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Cyclone Wind,0.000003,0.000013,5.000000e-07
2,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Extreme Heat,0.000000,0.992890,2.720250e-03
3,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Extreme Wind,0.000047,0.000414,3.400000e-06
4,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Forest Fire,0.000000,0.000000,0.000000e+00
5,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Freeze-Thaw,0.000000,0.000000,0.000000e+00
6,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Flooding,0.000000,0.000000,0.000000e+00
7,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Soil Subsidence,0.000000,0.000000,0.000000e+00
8,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Flooding,0.000000,0.000000,0.000000e+00
9,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2023,Coastal Inundation,0.000000,0.000000,0.000000e+00

In [21]:
import_hazard_type = [
"Coastal Inundation",
"Extreme Heat",
"Extreme Wind",
"Forest Fire",
"Freeze-Thaw",
"Riverine Flooding",
"Soil Subsidence",
"Surface Water Flooding",
"Flooding",
"Cyclone Wind"]

In [22]:
Hazard_Breakdown_df = Hazard_Breakdown_df[Hazard_Breakdown_df['Hazard'].isin(import_hazard_type)].reset_index(drop=True)

In [23]:
Hazard_Breakdown_df = Hazard_Breakdown_df.rename(columns={'HazMVAR':'avg_hazard_risk', 'HazFP' :'avg_hazard_fail'})

In [24]:
Hazard_computation_df =  Hazard_computation_df[Hazard_computation_df['Hazard'].isin(import_hazard_type)].reset_index(drop=True)
Hazard_computation_df['Hazard'] = Hazard_computation_df['Hazard'].apply(
    lambda x: 'Flooding' if x in ['Riverine Flooding', 'Surface Water Flooding'] else x
)

In [25]:
Hazard_computation_df

,Scenario,CompanyID,CompanyName,Country,Year,Hazard,SumHazMVAR,HazMVAR_Flag,SumHazFP,HazFP_Flag,SumHazPL
0,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Coastal Inundation,0.000000,0,0.000000,0,0.000000e+00
1,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Cyclone Wind,0.000003,0,0.000013,0,5.000000e-07
2,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Extreme Heat,0.000000,0,0.992890,1,2.720250e-03
3,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Extreme Wind,0.000047,0,0.000414,0,3.400000e-06
4,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,Forest Fire,0.000000,0,0.000000,0,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
4351,RCP2.6,1008128171,Barrick Gold Corp.,ZMB,2100,Forest Fire,0.000827,0,0.004330,0,1.067620e-03
4352,RCP2.6,1008128171,Barrick Gold Corp.,ZMB,2100,Freeze-Thaw,0.000000,0,0.000000,0,0.000000e+00
4353,RCP2.6,1008128171,Barrick Gold Corp.,ZMB,2100,Flooding,0.000000,0,0.000000,0,0.000000e+00
4354,RCP2.6,1008128171,Barrick Gold Corp.,ZMB,2100,Soil Subsidence,0.000000,0,0.000000,0,0.000000e+00
4355,RCP2.6,1008128171,Barrick Gold Corp.,ZMB,2100,Flooding,0.000000,0,0.000000,0,0.000000e+00

In [26]:
Hazard_computation_df = Hazard_computation_df.rename(columns={'SumHazMVAR':'sum_hazard_risk', 'HazMVAR_Flag':'flag','SumHazFP':'sum_hazard_fail','HazFP_Flag':'hazard_rate_flag'})

In [27]:
Hazard_computation_df.columns

Index(['Scenario', 'CompanyID', 'CompanyName', 'Country', 'Year', 'Hazard',
       'sum_hazard_risk', 'flag', 'sum_hazard_fail', 'hazard_rate_flag',
       'SumHazPL'],
      dtype='object')

In [28]:
combination = Hazard_computation_df.merge(Hazard_Breakdown_df, on=['Scenario', 'CompanyID', 'CompanyName', 'Country', 'Year', 'Hazard'])

In [29]:
hazard_rate = combination[['CompanyID', 'Scenario' , 'CompanyName', 'Country', 'Year', 'Hazard',
       'avg_hazard_fail','sum_hazard_fail', 'hazard_rate_flag']]

In [30]:
hazard_rate = hazard_rate.rename(columns = {'hazard_rate_flag':'flag'})
hazard_rate['fl_deleted'] = np.nan
hazard_rate.to_csv('hazard_rate.csv',index=False)

In [31]:
hazard_risk = combination[['CompanyID', 'Scenario' , 'CompanyName', 'Country', 'Year', 'Hazard',
       'avg_hazard_risk', 'sum_hazard_risk', 'flag']]

In [32]:
hazard_risk['fl_deleted'] = np.nan
hazard_risk.to_csv('hazard_risk.csv',index=False)
hazard_risk

C:\Users\jkumava\AppData\Local\Temp\ipykernel_37144\1366514972.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hazard_risk['fl_deleted'] = np.nan

,CompanyID,Scenario,CompanyName,Country,Year,Hazard,avg_hazard_risk,sum_hazard_risk,flag,fl_deleted
0,1008128171,RCP2.6,Barrick Gold Corp.,ARE,2022,Coastal Inundation,0.000000,0.000000,0,NaN
1,1008128171,RCP2.6,Barrick Gold Corp.,ARE,2022,Cyclone Wind,0.000003,0.000003,0,NaN
2,1008128171,RCP2.6,Barrick Gold Corp.,ARE,2022,Extreme Heat,0.000000,0.000000,0,NaN
3,1008128171,RCP2.6,Barrick Gold Corp.,ARE,2022,Extreme Wind,0.000047,0.000047,0,NaN
4,1008128171,RCP2.6,Barrick Gold Corp.,ARE,2022,Forest Fire,0.000000,0.000000,0,NaN
...,...,...,...,...,...,...,...,...,...,...
5319,1008128171,RCP2.6,Barrick Gold Corp.,ZMB,2100,Flooding,0.000000,0.000000,0,NaN
5320,1008128171,RCP2.6,Barrick Gold Corp.,ZMB,2100,Flooding,0.000000,0.000000,0,NaN
5321,1008128171,RCP2.6,Barrick Gold Corp.,ZMB,2100,Flooding,0.000000,0.000000,0,NaN
5322,1008128171,RCP2.6,Barrick Gold Corp.,ZMB,2100,Flooding,0.000000,0.000000,0,NaN
5323,1008128171,RCP2.6,Barrick Gold Corp.,ZMB,2100,Soil Subsidence,0.000000,0.000000,0,NaN

In [33]:
comb = Computation_df.merge(var_df,on=['Scenario', 'CompanyID', 'CompanyName', 'Country', 'Year'],how='outer')

In [34]:
risk_fraction = comb.rename(columns={'SumFP':'sum_fail_frac', 'SumMVAR':'sum_risk_fraction','MVAR' : 'avg_risk_fraction'})

In [35]:
risk_fraction[risk_fraction['sum_risk_fraction'] >= 0.0][risk_fraction['sum_risk_fraction'] <= 1.0]

,Scenario,CompanyID,CompanyName,Country,Year,sum_risk_fraction,sum_fail_frac,SumPL,avg_risk_fraction
0,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,0.000049,0.992893,0.002724,0.000049
1,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2023,0.000049,0.992893,0.002724,0.000049
2,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2025,0.000050,0.992893,0.002724,0.000050
3,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2027,0.000050,0.992893,0.002724,0.000050
4,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2028,0.000051,0.992893,0.002724,0.000051
...,...,...,...,...,...,...,...,...,...
479,RCP2.6,1008128171,Barrick Gold Corp.,ZMB,2035,0.000062,0.000502,0.000022,0.000062
480,RCP2.6,1008128171,Barrick Gold Corp.,ZMB,2040,0.000069,0.000537,0.000031,0.000069
481,RCP2.6,1008128171,Barrick Gold Corp.,ZMB,2045,0.000080,0.000597,0.000045,0.000080
482,RCP2.6,1008128171,Barrick Gold Corp.,ZMB,2050,0.000098,0.000708,0.000066,0.000098
483,RCP2.6,1008128171,Barrick Gold Corp.,ZMB,2100,0.000878,0.243289,0.001728,0.000878

### xdi_processing.udf_filter_hazard_risk

In [36]:
distinct_df = hazard_risk.sort_values(by=['Scenario', 'CompanyID', 'Country', 'Hazard', 'Year','avg_hazard_risk', 'sum_hazard_risk'], ascending=[True, True, True, True, True, False,False]).drop_duplicates(subset=['Scenario', 'CompanyID', 'Country', 'Hazard', 'Year'])
udf_filter_hazard_risk = distinct_df[['Scenario', 'CompanyID', 'Country', 'Hazard', 'Year', 'sum_hazard_risk', 'avg_hazard_risk', 'CompanyName','flag']].rename(columns={'flag': 'count_assets_with_asset_damage_risk'})

In [37]:
# udf_filter_hazard_risk[udf_filter_hazard_risk['Hazard']=='Flooding'][udf_filter_hazard_risk['Country'] =='USA']

In [38]:
# hazard_risk[hazard_risk['Hazard'] == 'Flooding'][hazard_risk['Country'] =='USA']

### xdi_processing.udf_select_prodloss()

In [39]:
hazard_outage = pd.DataFrame([
	{
		"outage_period" : 30,
		"hazard_type" : "Coastal Inundation"
	},
	{
		"outage_period" : 3,
		"hazard_type" : "Extreme Wind"
	},
	{
		"outage_period" : 90,
		"hazard_type" : "Forest Fire"
	},
	{
		"outage_period" : 0,
		"hazard_type" : "Freeze-Thaw"
	},
	{
		"outage_period" : 14,
		"hazard_type" : "Flooding"
	},
	{
		"outage_period" : 0,
		"hazard_type" : "Soil Subsidence"
	},
	{
		"outage_period" : 1,
		"hazard_type" : "Extreme Heat"
	},
	{
		"outage_period" : 7,
		"hazard_type" : "Cyclone Wind"
	}
])
hazard_outage

   outage_period         hazard_type
0             30  Coastal Inundation
1              3        Extreme Wind
2             90         Forest Fire
3              0         Freeze-Thaw
4             14            Flooding
5              0     Soil Subsidence
6              1        Extreme Heat
7              7        Cyclone Wind

In [40]:
grouped = hazard_rate.sort_values(by=['Scenario', 'CompanyID', 'Country', 'Hazard', 'Year','avg_hazard_fail','sum_hazard_fail','flag'], ascending=[True, True, True, True, True, False, False,False]).drop_duplicates(subset=['Scenario', 'CompanyID', 'Country', 'Hazard', 'Year'])

In [41]:
# testing code for validation 
# hazard_rate[hazard_rate['Hazard'] == 'Flooding'][hazard_rate['Country'] == 'USA'].sort_values(by=['Scenario', 'CompanyID', 'Country', 'Hazard', 'Year','avg_hazard_fail','sum_hazard_fail','flag'], ascending=[True, True, True, True, True, False, False, False])

In [42]:
final_df = pd.merge(grouped, hazard_outage, left_on= 'Hazard',right_on='hazard_type', how='left')

In [43]:
final_df['productive_capacity_loss'] = (final_df['avg_hazard_fail'] * final_df['outage_period']) / 365

In [44]:
final_df[['Country','Year','hazard_type','avg_hazard_fail','outage_period']][final_df[['Country','Year','hazard_type','avg_hazard_fail','outage_period']]['Country'] =='BEL']

    Country  Year         hazard_type  avg_hazard_fail  outage_period
264     BEL  2022  Coastal Inundation              0.0             30
265     BEL  2023  Coastal Inundation              0.0             30
266     BEL  2025  Coastal Inundation              0.0             30
267     BEL  2027  Coastal Inundation              0.0             30
268     BEL  2028  Coastal Inundation              0.0             30
..      ...   ...                 ...              ...            ...
347     BEL  2035     Soil Subsidence              0.0              0
348     BEL  2040     Soil Subsidence              0.0              0
349     BEL  2045     Soil Subsidence              0.0              0
350     BEL  2050     Soil Subsidence              0.0              0
351     BEL  2100     Soil Subsidence              0.0              0

[88 rows x 5 columns]

In [45]:
final_df['productive_capacity_loss_days'] = final_df['avg_hazard_fail'] * final_df['outage_period']

In [46]:
final_df['count_assets_with_prodloss'] = final_df['flag'].copy()

In [47]:
udf_select_prodloss = final_df[['CompanyID','Scenario',"Year","Country","CompanyName","hazard_type","productive_capacity_loss","productive_capacity_loss_days","count_assets_with_prodloss","sum_hazard_fail","avg_hazard_fail","outage_period"]]
udf_select_prodloss.head()

,CompanyID,Scenario,Year,Country,CompanyName,hazard_type,productive_capacity_loss,productive_capacity_loss_days,count_assets_with_prodloss,sum_hazard_fail,avg_hazard_fail,outage_period
0,1008128171,RCP2.6,2022,ARE,Barrick Gold Corp.,Coastal Inundation,0.0,0.0,0,0.0,0.0,30
1,1008128171,RCP2.6,2023,ARE,Barrick Gold Corp.,Coastal Inundation,0.0,0.0,0,0.0,0.0,30
2,1008128171,RCP2.6,2025,ARE,Barrick Gold Corp.,Coastal Inundation,0.0,0.0,0,0.0,0.0,30
3,1008128171,RCP2.6,2027,ARE,Barrick Gold Corp.,Coastal Inundation,0.0,0.0,0,0.0,0.0,30
4,1008128171,RCP2.6,2028,ARE,Barrick Gold Corp.,Coastal Inundation,0.0,0.0,0,0.0,0.0,30

In [48]:
# Test and comparing Zone
# final_df[final_df["Year"]==2023][['Country','productive_capacity_loss']]
udf_select_prodloss[udf_select_prodloss['Country'] == 'USA'][udf_select_prodloss['hazard_type'] == 'Flooding']

C:\Users\jkumava\AppData\Local\Temp\ipykernel_37144\3704258822.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  udf_select_prodloss[udf_select_prodloss['Country'] == 'USA'][udf_select_prodloss['hazard_type'] == 'Flooding']

,CompanyID,Scenario,Year,Country,CompanyName,hazard_type,productive_capacity_loss,productive_capacity_loss_days,count_assets_with_prodloss,sum_hazard_fail,avg_hazard_fail,outage_period
3652,1008128171,RCP2.6,2022,USA,Barrick Gold Corp.,Flooding,0.000052,0.018887,4,0.310281,0.001349,14
3653,1008128171,RCP2.6,2023,USA,Barrick Gold Corp.,Flooding,0.000052,0.018971,4,0.311661,0.001355,14
3654,1008128171,RCP2.6,2025,USA,Barrick Gold Corp.,Flooding,0.000052,0.019133,4,0.314335,0.001367,14
3655,1008128171,RCP2.6,2027,USA,Barrick Gold Corp.,Flooding,0.000053,0.019268,4,0.316550,0.001376,14
3656,1008128171,RCP2.6,2028,USA,Barrick Gold Corp.,Flooding,0.000053,0.019330,4,0.317569,0.001381,14
3657,1008128171,RCP2.6,2030,USA,Barrick Gold Corp.,Flooding,0.000053,0.019463,4,0.319745,0.001390,14
3658,1008128171,RCP2.6,2035,USA,Barrick Gold Corp.,Flooding,0.000055,0.020020,4,0.328896,0.001430,14
3659,1008128171,RCP2.6,2040,USA,Barrick Gold Corp.,Flooding,0.000057,0.020763,4,0.341107,0.001483,14
3660,1008128171,RCP2.6,2045,USA,Barrick Gold Corp.,Flooding,0.000060,0.021730,4,0.356993,0.001552,14
3661,1008128171,RCP2.6,2050,USA,Barrick Gold Corp.,Flooding,0.000062,0.022745,4,0.373673,0.001625,14
3662,1008128171,RCP2.6,2100,USA,Barrick Gold Corp.,Flooding,0.000072,0.026231,5,0.430937,0.001874,14

### xdi_processing.udf_select_all()

In [49]:
total_group = tzero_df.groupby(['CompanyID'])['Count'].sum().reset_index()
total_group.rename(columns={'Count': 'total_assets_count'}, inplace=True)
total_group

    CompanyID  total_assets_count
0  1008128171                 583

In [50]:
udf_filter_hazard_risk = udf_filter_hazard_risk.rename(columns={'Hazard' : 'hazard_type'})
merged_hr_p = pd.merge(udf_filter_hazard_risk, udf_select_prodloss,
                       on=['CompanyID','Scenario','CompanyName', 'Country' , 'hazard_type', 'Year'],how= 'outer')

In [51]:
merged_hr_p.head(2)

,Scenario,CompanyID,Country,hazard_type,Year,sum_hazard_risk,avg_hazard_risk,CompanyName,count_assets_with_asset_damage_risk,productive_capacity_loss,productive_capacity_loss_days,count_assets_with_prodloss,sum_hazard_fail,avg_hazard_fail,outage_period
0,RCP2.6,1008128171,ARE,Coastal Inundation,2022,0.0,0.0,Barrick Gold Corp.,0,0.0,0.0,0,0.0,0.0,30
1,RCP2.6,1008128171,ARE,Coastal Inundation,2023,0.0,0.0,Barrick Gold Corp.,0,0.0,0.0,0,0.0,0.0,30

In [52]:
merged_hr_p = merged_hr_p.merge(tzero_df,on=['CompanyID','CompanyName','Country'] ,how ='left')

In [53]:
merged_hr_p.head(2)

,Scenario,CompanyID,Country,hazard_type,Year,sum_hazard_risk,avg_hazard_risk,CompanyName,count_assets_with_asset_damage_risk,productive_capacity_loss,productive_capacity_loss_days,count_assets_with_prodloss,sum_hazard_fail,avg_hazard_fail,outage_period,Count,ReplacementCost,Turnover
0,RCP2.6,1008128171,ARE,Coastal Inundation,2022,0.0,0.0,Barrick Gold Corp.,0,0.0,0.0,0,0.0,0.0,30,1,1000000.0,2000000
1,RCP2.6,1008128171,ARE,Coastal Inundation,2023,0.0,0.0,Barrick Gold Corp.,0,0.0,0.0,0,0.0,0.0,30,1,1000000.0,2000000

In [54]:
merged_hr_p_tg = pd.merge(merged_hr_p, total_group,
                          on=['CompanyID'])

In [55]:
merged_hr_p_tg.head()

,Scenario,CompanyID,Country,hazard_type,Year,sum_hazard_risk,avg_hazard_risk,CompanyName,count_assets_with_asset_damage_risk,productive_capacity_loss,productive_capacity_loss_days,count_assets_with_prodloss,sum_hazard_fail,avg_hazard_fail,outage_period,Count,ReplacementCost,Turnover,total_assets_count
0,RCP2.6,1008128171,ARE,Coastal Inundation,2022,0.0,0.0,Barrick Gold Corp.,0,0.0,0.0,0,0.0,0.0,30,1,1000000.0,2000000,583
1,RCP2.6,1008128171,ARE,Coastal Inundation,2023,0.0,0.0,Barrick Gold Corp.,0,0.0,0.0,0,0.0,0.0,30,1,1000000.0,2000000,583
2,RCP2.6,1008128171,ARE,Coastal Inundation,2025,0.0,0.0,Barrick Gold Corp.,0,0.0,0.0,0,0.0,0.0,30,1,1000000.0,2000000,583
3,RCP2.6,1008128171,ARE,Coastal Inundation,2027,0.0,0.0,Barrick Gold Corp.,0,0.0,0.0,0,0.0,0.0,30,1,1000000.0,2000000,583
4,RCP2.6,1008128171,ARE,Coastal Inundation,2028,0.0,0.0,Barrick Gold Corp.,0,0.0,0.0,0,0.0,0.0,30,1,1000000.0,2000000,583

In [56]:
# # MERGE ALL CSV INTO ONE
# import pandas as pd
# import glob

# # Specify the path to the CSV files
# path = "C:/Users/jkumava/Downloads/PCRM/Corporate_data/"  # Adjust this to your CSV files' directory
# all_files = glob.glob(path + "*.csv")

# dfs = []

# for filename in all_files:
#     df = pd.read_csv(filename)
#     dfs.append(df)

# merged_df = pd.concat(dfs, ignore_index=True)

# merged_df.to_csv("C:/Users/jkumava/Downloads/PCRM/merged_file.csv", index=False)

In [57]:
corporate_data = pd.read_csv("C:/Users/jkumava/Downloads/PCRM/corporate_data.csv")

C:\Users\jkumava\AppData\Local\Temp\ipykernel_37144\2923511322.py:1: DtypeWarning: Columns (36) have mixed types. Specify dtype option on import or set low_memory=False.
  corporate_data = pd.read_csv("C:/Users/jkumava/Downloads/PCRM/corporate_data.csv")

In [58]:
corporate_data.head(2)

,sustcompanyid,industryname,subpeergroup,subpeergroupid,researchuniverse,industrygroup,hqlongitude,hqlatitude,sector,peergroup,...,spr_abr,esg_voting,corporate_governance_region_code,corporate_governance_region_name,lctr,sensitivity,esg_smart_score,impact_ratings,thematic_stewardship_programmes,eu_taxonomy_solutions
0,1009489602,Technology Hardware,Communications Equipment,45205110,NaN,Technology Hardware,77.672915,12.849138,Information Technology,Technology Hardware,...,11.0,11.0,IND,India,11.0,non-sensitive,99.0,99.0,11.0,11.0
1,2000000909,No longer available,Other Financial Services,40204710,0.0,NaN,NaN,NaN,Financials,Diversified Financials,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
corporate_data.columns

Index(['sustcompanyid', 'industryname', 'subpeergroup', 'subpeergroupid',
       'researchuniverse', 'industrygroup', 'hqlongitude', 'hqlatitude',
       'sector', 'peergroup', 'sustisin', 'companytypesus', 'subindustrycode',
       'subindustry', 'companynamesus', 'templatetype',
       'internalproductuniverse', 'esgcomprehensive', 'incidents',
       'globalcompact', 'productinvolvement', 'governance', 'esgcore',
       'esgriskratings', 'coreesgriskratings', 'carbon', 'entityrationale',
       'researchentityid', 'entitytype', 'carbonriskratings', 'gss',
       'countryratings', 'solutions', 'cwr', 'dt_created', 'dt_updated',
       'fl_deleted', 'internalcompanyid', 'clientindustryid',
       'clientindustryname', 'clientsubindustryid', 'clientsubindustryname',
       'hrr', 'esgimpactmetrics', 'mre', 'sovereignregion_code',
       'sovereignregion_name', 'incomegroup', 'eligibilityclass',
       'eligibilityclass_rationale', 'eu_taxonomy', 'sfdr_corporate',
       'sfdr_sovereign', 'bmr_corporate', 'bmr_sovereign', 'esg_data',
       'physical_impact', 'engagement_360', 'muni', 'spr_abr', 'esg_voting',
       'corporate_governance_region_code', 'corporate_governance_region_name',
       'lctr', 'sensitivity', 'esg_smart_score', 'impact_ratings',
       'thematic_stewardship_programmes', 'eu_taxonomy_solutions'],
      dtype='object')

In [60]:
corporate_data_templates = corporate_data[['sustcompanyid', 'clientindustryid','clientindustryname','peergroup']]

In [61]:
corporate_data_templates = corporate_data_templates.dropna().reset_index(drop=True)
corporate_data_templates.dtypes

sustcompanyid           int64
clientindustryid      float64
clientindustryname     object
peergroup              object
dtype: object

In [62]:
merged_hr_p_tg['CompanyID'] = merged_hr_p_tg['CompanyID'].astype(int)

In [63]:
final_df = pd.merge(merged_hr_p_tg, corporate_data_templates,
                    left_on='CompanyID', right_on='sustcompanyid', how='left')

In [64]:
final_df['percent_of_assets_in_country'] = final_df['Count'] / final_df['total_assets_count'].replace({0: pd.NA})
final_df['weighted_avg_hazard_risk'] = (final_df['Count'] * final_df['avg_hazard_risk']) / final_df['total_assets_count'].replace({0: pd.NA})
final_df['weighted_prodloss'] = (final_df['Count'] * final_df['productive_capacity_loss']) / final_df['total_assets_count'].replace({0: pd.NA})
final_df['weighted_productive_capacity_loss_days'] = final_df['total_assets_count'] * final_df['productive_capacity_loss_days']

In [65]:
final_df.columns

Index(['Scenario', 'CompanyID', 'Country', 'hazard_type', 'Year',
       'sum_hazard_risk', 'avg_hazard_risk', 'CompanyName',
       'count_assets_with_asset_damage_risk', 'productive_capacity_loss',
       'productive_capacity_loss_days', 'count_assets_with_prodloss',
       'sum_hazard_fail', 'avg_hazard_fail', 'outage_period', 'Count',
       'ReplacementCost', 'Turnover', 'total_assets_count', 'sustcompanyid',
       'clientindustryid', 'clientindustryname', 'peergroup',
       'percent_of_assets_in_country', 'weighted_avg_hazard_risk',
       'weighted_prodloss', 'weighted_productive_capacity_loss_days'],
      dtype='object')

In [66]:
final_df = final_df.merge(fmi_df.rename(columns = {
    "CompanyID" : "sustcompanyid" }), on = ['Scenario', 'sustcompanyid', 'CompanyName', 'Country', 'Year'])
final_df['indirect_probability'] = final_df['FMI'] - final_df['productive_capacity_loss'] * final_df['FMI']

In [67]:
df_full = final_df[['Scenario', 'sustcompanyid', 'Country', 'peergroup','hazard_type', 'Year',
       'sum_hazard_risk', 'avg_hazard_risk', 'CompanyName',
       'count_assets_with_asset_damage_risk', 'productive_capacity_loss',
       'productive_capacity_loss_days', 'count_assets_with_prodloss',
        'outage_period', 'Count',
       'ReplacementCost', 'Turnover', 'total_assets_count',
       'clientindustryid', 'clientindustryname',
       'percent_of_assets_in_country', 'weighted_avg_hazard_risk',
       'weighted_prodloss', 'weighted_productive_capacity_loss_days','indirect_probability']]

In [69]:
# Verification of calculation for Global_table
# df_full.groupby(['Scenario', 'sustcompanyid', 'Year'], as_index=False)["weighted_productive_capacity_loss_days"].sum()
df_full.to_csv('df_full_calculated.csv', index=False)

In [70]:
df_import_years = pd.DataFrame( [
	{
		"year" : 2030,
		"active" : 1,
		"table_name" : "damage"
	},
	{
		"year" : 2050,
		"active" : 1,
		"table_name" : "damage"
	},
	{
		"year" : 2035,
		"active" : 1,
		"table_name" : "damage"
	},
	{
		"year" : 2040,
		"active" : 1,
		"table_name" : "damage"
	},
	{
		"year" : 2045,
		"active" : 1,
		"table_name" : "damage"
	},
	{
		"year" : 2025,
		"active" : 1,
		"table_name" : "damage"
	},
	{
		"year" : 2030,
		"active" : 1,
		"table_name" : "global"
	},
	{
		"year" : 2050,
		"active" : 1,
		"table_name" : "global"
	},
	{
		"year" : 2100,
		"active" : 1,
		"table_name" : "global"
	},
	{
		"year" : 2023,
		"active" : 1,
		"table_name" : "damage"
	},
	{
		"year" : 2023,
		"active" : 1,
		"table_name" : "global"
	},
    {
		"year" : 2027,
		"active" : 1,
		"table_name" : "global"
	},
	{
		"year" : 2028,
		"active" : 1,
		"table_name" : "global"
	},
	{
		"year" : 2022,
		"active" : 1,
		"table_name" : "global"
	}
])
df_import_years

    year  active table_name
0   2030       1     damage
1   2050       1     damage
2   2035       1     damage
3   2040       1     damage
4   2045       1     damage
5   2025       1     damage
6   2030       1     global
7   2050       1     global
8   2100       1     global
9   2023       1     damage
10  2023       1     global
11  2027       1     global
12  2028       1     global
13  2022       1     global

## Country Risk Calculations

In [71]:
import_years = df_import_years[(df_import_years['active'] == True) & (df_import_years['table_name'] == 'global')]

In [72]:
import_years = import_years.sort_values(by='year')

In [73]:
global_haz1 = df_full.merge(import_years[['year']], left_on='Year', right_on='year',how='inner')
# global_haz1 = global_haz.sort_values(by = 'Year').reset_index(drop=True)
# global_haz1['clientindustryid'] = global_haz1['clientindustryid'].astype(int)

In [74]:
global_haz1.Year.unique()
global_haz1
# df_full.merge(import_years[['year']], left_on='Year', right_on='year',how='inner')

,Scenario,sustcompanyid,Country,peergroup,hazard_type,Year,sum_hazard_risk,avg_hazard_risk,CompanyName,count_assets_with_asset_damage_risk,...,Turnover,total_assets_count,clientindustryid,clientindustryname,percent_of_assets_in_country,weighted_avg_hazard_risk,weighted_prodloss,weighted_productive_capacity_loss_days,indirect_probability,year
0,RCP2.6,1008128171,ARE,Precious Metals,Coastal Inundation,2022,0.000000,0.000000,Barrick Gold Corp.,0,...,2000000,583,151019.0,Precious Metals,0.001715,0.000000e+00,0.000000e+00,0.000000,0.001993,2022
1,RCP2.6,1008128171,ARE,Precious Metals,Cyclone Wind,2022,0.000003,0.000003,Barrick Gold Corp.,0,...,2000000,583,151019.0,Precious Metals,0.001715,4.442539e-09,4.286285e-10,0.053175,0.001993,2022
2,RCP2.6,1008128171,ARE,Precious Metals,Extreme Heat,2022,0.000000,0.000000,Barrick Gold Corp.,0,...,2000000,583,151019.0,Precious Metals,0.001715,0.000000e+00,4.665946e-06,578.854853,0.001988,2022
3,RCP2.6,1008128171,ARE,Precious Metals,Extreme Wind,2022,0.000047,0.000047,Barrick Gold Corp.,0,...,2000000,583,151019.0,Precious Metals,0.001715,7.989708e-08,5.836462e-09,0.724069,0.001993,2022
4,RCP2.6,1008128171,ARE,Precious Metals,Flooding,2022,0.000000,0.000000,Barrick Gold Corp.,0,...,2000000,583,151019.0,Precious Metals,0.001715,0.000000e+00,0.000000e+00,0.000000,0.001993,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2459,RCP2.6,1008128171,ZMB,Precious Metals,Extreme Wind,2100,0.000051,0.000051,Barrick Gold Corp.,0,...,2000000,583,151019.0,Precious Metals,0.001715,8.804460e-08,6.430837e-09,0.797806,0.012292,2100
2460,RCP2.6,1008128171,ZMB,Precious Metals,Flooding,2100,0.000000,0.000000,Barrick Gold Corp.,0,...,2000000,583,151019.0,Precious Metals,0.001715,0.000000e+00,0.000000e+00,0.000000,0.012292,2100
2461,RCP2.6,1008128171,ZMB,Precious Metals,Forest Fire,2100,0.000827,0.000827,Barrick Gold Corp.,0,...,2000000,583,151019.0,Precious Metals,0.001715,1.418765e-06,1.831255e-06,227.184606,0.012279,2100
2462,RCP2.6,1008128171,ZMB,Precious Metals,Freeze-Thaw,2100,0.000000,0.000000,Barrick Gold Corp.,0,...,2000000,583,151019.0,Precious Metals,0.001715,0.000000e+00,0.000000e+00,0.000000,0.012292,2100
2463,RCP2.6,1008128171,ZMB,Precious Metals,Soil Subsidence,2100,0.000000,0.000000,Barrick Gold Corp.,0,...,2000000,583,151019.0,Precious Metals,0.001715,0.000000e+00,0.000000e+00,0.000000,0.012292,2100

In [75]:
global_haz = global_haz1.groupby(['Scenario', 'clientindustryid', 'sustcompanyid', 'Year', 'hazard_type']).agg(
        avg_hazard_risk=('avg_hazard_risk', 'mean'),
        weighted_avg_hazard_risk=('weighted_avg_hazard_risk', 'sum'),
        productive_capacity_loss=('productive_capacity_loss', 'mean'),
        productive_capacity_loss_days=('productive_capacity_loss_days', 'sum'),
        weighted_prodloss=('weighted_prodloss', 'sum'),
        weighted_productive_capacity_loss_days = ('weighted_productive_capacity_loss_days', 'sum'),
        count_assets_with_asset_damage_risk=('count_assets_with_asset_damage_risk', 'sum'),
        count_assets_with_prodloss=('count_assets_with_prodloss', 'sum'),
        total_assets_count=('total_assets_count', 'max')
    ).reset_index()
global_haz.head()

,Scenario,clientindustryid,sustcompanyid,Year,hazard_type,avg_hazard_risk,weighted_avg_hazard_risk,productive_capacity_loss,productive_capacity_loss_days,weighted_prodloss,weighted_productive_capacity_loss_days,count_assets_with_asset_damage_risk,count_assets_with_prodloss,total_assets_count
0,RCP2.6,151019.0,1008128171,2022,Coastal Inundation,0.000262,0.000482,0.000089,1.432547,1.280742e-04,835.174784,3,3,583
1,RCP2.6,151019.0,1008128171,2022,Cyclone Wind,0.000016,0.000009,0.000002,0.024816,8.553974e-07,14.467716,0,0,583
2,RCP2.6,151019.0,1008128171,2022,Extreme Heat,0.000000,0.000000,0.000632,10.150864,5.704011e-04,5917.953695,0,253,583
3,RCP2.6,151019.0,1008128171,2022,Extreme Wind,0.000049,0.000053,0.000004,0.057140,3.804318e-06,33.312626,0,0,583
4,RCP2.6,151019.0,1008128171,2022,Flooding,0.000805,0.000733,0.000139,2.227087,1.244620e-04,1298.391861,22,40,583

In [76]:
global_all_full = global_haz.rename(columns={'Scenario':'rcp_scenario'}).groupby(['rcp_scenario', 'clientindustryid', 'sustcompanyid', 'Year']).agg(
        avg_hazard_risk=('avg_hazard_risk', 'sum'),
        overall_asset_damage_risk=('weighted_avg_hazard_risk', 'sum'),
        productive_capacity_loss=('productive_capacity_loss', 'sum'),
        productive_capacity_loss_days=('productive_capacity_loss_days', 'sum'),
        overall_productive_capacity_loss=('weighted_prodloss', 'sum'),
        overall_productive_capacity_loss_days = ('weighted_productive_capacity_loss_days' , 'sum'),
        count_assets_with_asset_damage_risk=('count_assets_with_asset_damage_risk', 'max'),
        count_assets_with_prodloss=('count_assets_with_prodloss', 'max'),
        total_assets_count=('total_assets_count', 'max')
    ).reset_index()

global_all_full['clientindustryid'] = global_all_full['clientindustryid'].astype(int)

In [77]:

global_all = global_all_full[['sustcompanyid','rcp_scenario', 'clientindustryid','Year', 'overall_asset_damage_risk',
       'overall_productive_capacity_loss']]

In [78]:
global_all

,sustcompanyid,rcp_scenario,clientindustryid,Year,overall_asset_damage_risk,overall_productive_capacity_loss
0,1008128171,RCP2.6,151019,2022,0.001682,0.001052
1,1008128171,RCP2.6,151019,2023,0.001689,0.001059
2,1008128171,RCP2.6,151019,2027,0.001714,0.001085
3,1008128171,RCP2.6,151019,2028,0.001722,0.001092
4,1008128171,RCP2.6,151019,2030,0.001726,0.001102
5,1008128171,RCP2.6,151019,2050,0.001949,0.001297
6,1008128171,RCP2.6,151019,2100,0.006829,0.002675

In [79]:
global_country = df_full.groupby(['Scenario', 'clientindustryid', 'sustcompanyid', 'Year', 'Country']).agg(
        avg_hazard_risk=('avg_hazard_risk', 'sum'),
        productive_capacity_loss=('productive_capacity_loss', 'sum'),
        count_assets_with_asset_damage_risk=('count_assets_with_asset_damage_risk', 'max'),
        count_assets_with_prodloss=('count_assets_with_prodloss', 'max'),
        percent_of_assets_in_country=('percent_of_assets_in_country', 'max'),
        total_assets_count=('total_assets_count', 'max')
    ).reset_index()

In [80]:
global_country.head()

,Scenario,clientindustryid,sustcompanyid,Year,Country,avg_hazard_risk,productive_capacity_loss,count_assets_with_asset_damage_risk,count_assets_with_prodloss,percent_of_assets_in_country,total_assets_count
0,RCP2.6,151019.0,1008128171,2022,ARE,0.000049,0.002724,0,1,0.001715,583
1,RCP2.6,151019.0,1008128171,2022,ARG,0.000049,0.000021,0,1,0.008576,583
2,RCP2.6,151019.0,1008128171,2022,AUS,0.003942,0.001244,9,24,0.183533,583
3,RCP2.6,151019.0,1008128171,2022,BEL,0.000496,0.000105,0,1,0.001715,583
4,RCP2.6,151019.0,1008128171,2022,BFA,0.000045,0.002723,0,2,0.003431,583

In [81]:
rei_df = rei_df.rename(columns={'CompanyID' : 'sustcompanyid'})
rei_df['sustcompanyid'] = rei_df['sustcompanyid'].astype(int)
rei_df.head()

  Scenario  sustcompanyid         CompanyName Country  Year       REI
0   RCP2.6     1008128171  Barrick Gold Corp.     ARE  2022  0.005404
1   RCP2.6     1008128171  Barrick Gold Corp.     ARE  2023  0.005404
2   RCP2.6     1008128171  Barrick Gold Corp.     ARE  2025  0.005404
3   RCP2.6     1008128171  Barrick Gold Corp.     ARE  2027  0.005404
4   RCP2.6     1008128171  Barrick Gold Corp.     ARE  2028  0.005404

In [82]:

tmp_infra = global_country.merge(rei_df, on=['sustcompanyid', 'Scenario', 'Year', 'Country'], 
                                           how='left')
tmp_infra['weighted_avg_regional_infrastructure_risk'] = tmp_infra['percent_of_assets_in_country'] * tmp_infra['REI']

In [83]:
tmp_infra['clientindustryid'] = tmp_infra['clientindustryid'].astype(int)
tmp_infra.head()

,Scenario,clientindustryid,sustcompanyid,Year,Country,avg_hazard_risk,productive_capacity_loss,count_assets_with_asset_damage_risk,count_assets_with_prodloss,percent_of_assets_in_country,total_assets_count,CompanyName,REI,weighted_avg_regional_infrastructure_risk
0,RCP2.6,151019,1008128171,2022,ARE,0.000049,0.002724,0,1,0.001715,583,Barrick Gold Corp.,0.005404,0.000009
1,RCP2.6,151019,1008128171,2022,ARG,0.000049,0.000021,0,1,0.008576,583,Barrick Gold Corp.,0.002731,0.000023
2,RCP2.6,151019,1008128171,2022,AUS,0.003942,0.001244,9,24,0.183533,583,Barrick Gold Corp.,0.001680,0.000308
3,RCP2.6,151019,1008128171,2022,BEL,0.000496,0.000105,0,1,0.001715,583,Barrick Gold Corp.,0.000951,0.000002
4,RCP2.6,151019,1008128171,2022,BFA,0.000045,0.002723,0,2,0.003431,583,Barrick Gold Corp.,0.001095,0.000004

In [84]:
country_infrastructure =  tmp_infra.groupby(['sustcompanyid', 'Scenario', 'Country', 'Year'],as_index=False).agg(
    avg_rei=('REI', 'mean')).merge( tmp_infra.groupby(['sustcompanyid', 'Scenario', 'Year'],as_index=False).agg(
    overall_weighted_rei=('weighted_avg_regional_infrastructure_risk', 'sum')),on = ['sustcompanyid', 'Scenario', 'Year'], how='left')

In [85]:
country_infrastructure.head(5)

   sustcompanyid Scenario Country  Year   avg_rei  overall_weighted_rei
0     1008128171   RCP2.6     ARE  2022  0.005404              0.002060
1     1008128171   RCP2.6     ARE  2023  0.005404              0.002065
2     1008128171   RCP2.6     ARE  2025  0.005404              0.002085
3     1008128171   RCP2.6     ARE  2027  0.005404              0.002108
4     1008128171   RCP2.6     ARE  2028  0.005404              0.002114

In [86]:
fmi_df = fmi_df.rename(columns={'CompanyID' : 'sustcompanyid'})
fmi_df['sustcompanyid'] = fmi_df['sustcompanyid'].astype(int)

In [87]:
tmp_local_infra = global_country.merge(fmi_df, on=['sustcompanyid', 'Scenario', 'Year', 'Country'], 
                                           how='left')

In [88]:
tmp_local_infra['weighted_avg_fmi'] = tmp_local_infra['percent_of_assets_in_country'] * tmp_local_infra['FMI']
tmp_local_infra['clientindustryid'] = tmp_local_infra['clientindustryid'].astype(int)

In [89]:
country_local_critical_infrastructure =  tmp_local_infra.groupby(['sustcompanyid', 'Scenario', 'Country', 'Year'],as_index=False).agg(
    avg_fmi=('FMI', 'mean')).merge( tmp_local_infra.groupby(['sustcompanyid', 'Scenario', 'Year'],as_index=False).agg(
    overall_weighted_fmi=('weighted_avg_fmi', 'sum')),on = ['sustcompanyid', 'Scenario', 'Year'], how='left')

country_local_critical_infrastructure

     sustcompanyid Scenario Country  Year   avg_fmi  overall_weighted_fmi
0       1008128171   RCP2.6     ARE  2022  0.001993              0.003771
1       1008128171   RCP2.6     ARE  2023  0.002134              0.003811
2       1008128171   RCP2.6     ARE  2025  0.002413              0.003889
3       1008128171   RCP2.6     ARE  2027  0.002793              0.003975
4       1008128171   RCP2.6     ARE  2028  0.002981              0.004016
..             ...      ...     ...   ...       ...                   ...
479     1008128171   RCP2.6     ZMB  2035  0.009765              0.004433
480     1008128171   RCP2.6     ZMB  2040  0.010616              0.004798
481     1008128171   RCP2.6     ZMB  2045  0.011426              0.005270
482     1008128171   RCP2.6     ZMB  2050  0.012038              0.005841
483     1008128171   RCP2.6     ZMB  2100  0.012292              0.011719

[484 rows x 6 columns]

In [90]:
global_country = global_country.rename(columns={'Scenario':'rcp_scenario'})
udf_select_country_final = global_country.merge(global_all, on=['sustcompanyid','clientindustryid', 'rcp_scenario', 'Year'])

In [91]:

counts_df = counts_df.rename(columns = {"Scenario" : "rcp_scenario", 'CompanyID' : 'sustcompanyid' })
counts_df['sustcompanyid'] = pd.to_numeric(counts_df['sustcompanyid'], errors = 'coerce')
udf_select_country_final = udf_select_country_final.merge(counts_df, on=['sustcompanyid', 'rcp_scenario', 'Year','Country'] )

In [92]:
country_infrastructure = country_infrastructure.rename(columns = {"Scenario" : "rcp_scenario", 'CompanyID' : 'sustcompanyid' })
udf_select_country_final = udf_select_country_final.merge(country_infrastructure, 
                                                              on=[ 'sustcompanyid', 'rcp_scenario', 'Year','Country'],
                                                              how='left')
udf_select_country_final.head()

,rcp_scenario,clientindustryid,sustcompanyid,Year,Country,avg_hazard_risk,productive_capacity_loss,count_assets_with_asset_damage_risk,count_assets_with_prodloss,percent_of_assets_in_country,total_assets_count,overall_asset_damage_risk,overall_productive_capacity_loss,CompanyName,count_uninsured,count_0_2_pct,count_0_5_pct,avg_rei,overall_weighted_rei
0,RCP2.6,151019.0,1008128171,2022,ARE,0.000049,0.002724,0,1,0.001715,583,0.001682,0.001052,Barrick Gold Corp.,0,0,1,0.005404,0.00206
1,RCP2.6,151019.0,1008128171,2022,ARG,0.000049,0.000021,0,1,0.008576,583,0.001682,0.001052,Barrick Gold Corp.,0,0,5,0.002731,0.00206
2,RCP2.6,151019.0,1008128171,2022,AUS,0.003942,0.001244,9,24,0.183533,583,0.001682,0.001052,Barrick Gold Corp.,10,8,89,0.001680,0.00206
3,RCP2.6,151019.0,1008128171,2022,BEL,0.000496,0.000105,0,1,0.001715,583,0.001682,0.001052,Barrick Gold Corp.,0,0,1,0.000951,0.00206
4,RCP2.6,151019.0,1008128171,2022,BFA,0.000045,0.002723,0,2,0.003431,583,0.001682,0.001052,Barrick Gold Corp.,0,0,2,0.001095,0.00206

In [93]:
country_local_critical_infrastructure = country_local_critical_infrastructure.rename(columns = {"Scenario" : "rcp_scenario", 'CompanyID' : 'sustcompanyid' })
udf_select_country_final = udf_select_country_final.merge(country_local_critical_infrastructure, 
                                                              on=['sustcompanyid', 'rcp_scenario', 'Year','Country'],
                                                              how='left')
udf_select_country_final

,rcp_scenario,clientindustryid,sustcompanyid,Year,Country,avg_hazard_risk,productive_capacity_loss,count_assets_with_asset_damage_risk,count_assets_with_prodloss,percent_of_assets_in_country,...,overall_asset_damage_risk,overall_productive_capacity_loss,CompanyName,count_uninsured,count_0_2_pct,count_0_5_pct,avg_rei,overall_weighted_rei,avg_fmi,overall_weighted_fmi
0,RCP2.6,151019.0,1008128171,2022,ARE,0.000049,0.002724,0,1,0.001715,...,0.001682,0.001052,Barrick Gold Corp.,0,0,1,0.005404,0.00206,0.001993,0.003771
1,RCP2.6,151019.0,1008128171,2022,ARG,0.000049,0.000021,0,1,0.008576,...,0.001682,0.001052,Barrick Gold Corp.,0,0,5,0.002731,0.00206,0.002152,0.003771
2,RCP2.6,151019.0,1008128171,2022,AUS,0.003942,0.001244,9,24,0.183533,...,0.001682,0.001052,Barrick Gold Corp.,10,8,89,0.001680,0.00206,0.010161,0.003771
3,RCP2.6,151019.0,1008128171,2022,BEL,0.000496,0.000105,0,1,0.001715,...,0.001682,0.001052,Barrick Gold Corp.,0,0,1,0.000951,0.00206,0.000820,0.003771
4,RCP2.6,151019.0,1008128171,2022,BFA,0.000045,0.002723,0,2,0.003431,...,0.001682,0.001052,Barrick Gold Corp.,0,0,2,0.001095,0.00206,0.002508,0.003771
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,RCP2.6,151019.0,1008128171,2100,TWN,0.001177,0.000311,0,1,0.005146,...,0.006829,0.002675,Barrick Gold Corp.,0,1,2,0.006252,0.00379,0.004765,0.011719
304,RCP2.6,151019.0,1008128171,2100,TZA,0.000060,0.000156,0,13,0.027444,...,0.006829,0.002675,Barrick Gold Corp.,0,0,16,0.001721,0.00379,0.000838,0.011719
305,RCP2.6,151019.0,1008128171,2100,USA,0.002960,0.001893,4,213,0.394511,...,0.006829,0.002675,Barrick Gold Corp.,12,14,204,0.003735,0.00379,0.005565,0.011719
306,RCP2.6,151019.0,1008128171,2100,ZAF,0.000113,0.000429,0,3,0.005146,...,0.006829,0.002675,Barrick Gold Corp.,0,0,3,0.001434,0.00379,0.001799,0.011719
307,RCP2.6,151019.0,1008128171,2100,ZMB,0.000878,0.001728,0,1,0.001715,...,0.006829,0.002675,Barrick Gold Corp.,0,0,1,0.001840,0.00379,0.012292,0.011719

In [94]:
udf_select_country_final['country_contribution_percentage_asset_damage_risk'] = (
        udf_select_country_final['avg_hazard_risk'] * udf_select_country_final['percent_of_assets_in_country'] * 100 /
        udf_select_country_final['overall_asset_damage_risk']
    ).fillna(0).round(0).astype(int)

In [95]:
udf_select_country_final['country_contribution_percentage_productive_capacity_loss'] = (
        udf_select_country_final['productive_capacity_loss'] * udf_select_country_final['percent_of_assets_in_country'] * 100 /
        udf_select_country_final['overall_productive_capacity_loss']
    ).fillna(0).round(0).astype(int)

In [96]:
udf_select_country_final['country_contribution_percentage_high_risk_assets'] = (
        100 * udf_select_country_final['count_uninsured'] / 
        udf_select_country_final.groupby(['sustcompanyid', 'rcp_scenario', 'Year'])['count_uninsured'].transform('sum')
    ).fillna(0).round(0).astype(int)
udf_select_country_final['country_high_risk_assets_percentage'] = (
        udf_select_country_final['count_uninsured'] / udf_select_country_final['total_assets_count']
    ).fillna(0)

In [97]:
udf_select_country_final['percentage_local_critical_infrastructure_risk'] = (
        udf_select_country_final['avg_fmi'] * udf_select_country_final['percent_of_assets_in_country'] * 100 /
        udf_select_country_final['overall_weighted_fmi']
    )#.fillna(0).round(0).astype(int)

udf_select_country_final['percentage_local_critical_infrastructure_risk'].replace([np.inf, -np.inf], np.nan, inplace=True)
udf_select_country_final['percentage_local_critical_infrastructure_risk'] = udf_select_country_final['percentage_local_critical_infrastructure_risk'].round(0)
udf_select_country_final['percentage_local_critical_infrastructure_risk'] = udf_select_country_final['percentage_local_critical_infrastructure_risk'].astype('Int64')

In [98]:
udf_select_country_final['country_contribution_percentage_regional_infrastructure_risk'] = (
        udf_select_country_final['avg_rei'] * udf_select_country_final['percent_of_assets_in_country'] * 100 /
        udf_select_country_final['overall_weighted_rei']
    ).fillna(0).round(0).astype(int)

In [99]:
udf_select_country_final = udf_select_country_final.rename(columns = {'avg_hazard_risk':'country_asset_damage_risk', 'productive_capacity_loss':'country_productive_capacity_loss'})
# [['REI','country_asset_damage_risk']]

### FMI values has some differences that's why it's not matching exactly with database final country_risk table
### RCP2.6	ID_1008128171	Barrick Gold Corp.	ARE	2023	0.0021343 # from XDI CSV file
### 1008128171	RCP2.6	ARE	2023	0.000216645  # from Database

In [100]:
udf_select_country_final = udf_select_country_final.rename(columns = {
    'sustcompanyid' : "entity_id", "Year":'physical_impact_year' , "Country":"country_iso3"
})

In [101]:
udf_select_country_final

,rcp_scenario,clientindustryid,entity_id,physical_impact_year,country_iso3,country_asset_damage_risk,country_productive_capacity_loss,count_assets_with_asset_damage_risk,count_assets_with_prodloss,percent_of_assets_in_country,...,avg_rei,overall_weighted_rei,avg_fmi,overall_weighted_fmi,country_contribution_percentage_asset_damage_risk,country_contribution_percentage_productive_capacity_loss,country_contribution_percentage_high_risk_assets,country_high_risk_assets_percentage,percentage_local_critical_infrastructure_risk,country_contribution_percentage_regional_infrastructure_risk
0,RCP2.6,151019.0,1008128171,2022,ARE,0.000049,0.002724,0,1,0.001715,...,0.005404,0.00206,0.001993,0.003771,0,0,0,0.000000,0,0
1,RCP2.6,151019.0,1008128171,2022,ARG,0.000049,0.000021,0,1,0.008576,...,0.002731,0.00206,0.002152,0.003771,0,0,0,0.000000,0,1
2,RCP2.6,151019.0,1008128171,2022,AUS,0.003942,0.001244,9,24,0.183533,...,0.001680,0.00206,0.010161,0.003771,43,22,36,0.017153,49,15
3,RCP2.6,151019.0,1008128171,2022,BEL,0.000496,0.000105,0,1,0.001715,...,0.000951,0.00206,0.000820,0.003771,0,0,0,0.000000,0,0
4,RCP2.6,151019.0,1008128171,2022,BFA,0.000045,0.002723,0,2,0.003431,...,0.001095,0.00206,0.002508,0.003771,0,1,0,0.000000,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,RCP2.6,151019.0,1008128171,2100,TWN,0.001177,0.000311,0,1,0.005146,...,0.006252,0.00379,0.004765,0.011719,0,0,0,0.000000,0,1
304,RCP2.6,151019.0,1008128171,2100,TZA,0.000060,0.000156,0,13,0.027444,...,0.001721,0.00379,0.000838,0.011719,0,0,0,0.000000,0,1
305,RCP2.6,151019.0,1008128171,2100,USA,0.002960,0.001893,4,213,0.394511,...,0.003735,0.00379,0.005565,0.011719,17,28,28,0.020583,19,39
306,RCP2.6,151019.0,1008128171,2100,ZAF,0.000113,0.000429,0,3,0.005146,...,0.001434,0.00379,0.001799,0.011719,0,0,0,0.000000,0,0
307,RCP2.6,151019.0,1008128171,2100,ZMB,0.000878,0.001728,0,1,0.001715,...,0.001840,0.00379,0.012292,0.011719,0,0,0,0.000000,0,0

## Tier Conditions

In [102]:
# tier_conditions =  pd.DataFrame([
# 	{
# 		"tier" : "Highest",
# 		"lowerbound" : 0.800,
# 		"upperbound" : 1.000,
# 		"tier_type" : "company"
# 	},
# 	{
# 		"tier" : "High",
# 		"lowerbound" : 0.600,
# 		"upperbound" : 0.800,
# 		"tier_type" : "company"
# 	},
# 	{
# 		"tier" : "Moderate",
# 		"lowerbound" : 0.400,
# 		"upperbound" : 0.600,
# 		"tier_type" : "company"
# 	},
# 	{
# 		"tier" : "Low",
# 		"lowerbound" : 0.200,
# 		"upperbound" : 0.400,
# 		"tier_type" : "company"
# 	},
# 	{
# 		"tier" : "Moderate",
# 		"lowerbound" : 5.000,
# 		"upperbound" : 25.000,
# 		"tier_type" : "country"
# 	},
# 	{
# 		"tier" : "Significant",
# 		"lowerbound" : 25.000,
# 		"upperbound" : 50.000,
# 		"tier_type" : "country"
# 	},
# 	{
# 		"tier" : "Leading",
# 		"lowerbound" : 50.000,
# 		"upperbound" : 100.000,
# 		"tier_type" : "country"
# 	},
# 	{
# 		"tier" : "Below Average",
# 		"lowerbound" : 20.000,
# 		"upperbound" : 40.000,
# 		"tier_type" : "global"
# 	},
# 	{
# 		"tier" : "Average",
# 		"lowerbound" : 40.000,
# 		"upperbound" : 60.000,
# 		"tier_type" : "global"
# 	},
# 	{
# 		"tier" : "Above Average",
# 		"lowerbound" : 60.000,
# 		"upperbound" : 80.000,
# 		"tier_type" : "global"
# 	},
# 	{
# 		"tier" : "Significantly Above Average",
# 		"lowerbound" : 80.000,
# 		"upperbound" : 100.000,
# 		"tier_type" : "global"
# 	},
# 	{
# 		"tier" : "Moderate",
# 		"lowerbound" : 5.000,
# 		"upperbound" : 25.000,
# 		"tier_type" : "hazard"
# 	},
# 	{
# 		"tier" : "Significant",
# 		"lowerbound" : 25.000,
# 		"upperbound" : 50.000,
# 		"tier_type" : "hazard"
# 	},
# 	{
# 		"tier" : "Leading",
# 		"lowerbound" : 50.000,
# 		"upperbound" : 100.000,
# 		"tier_type" : "hazard"
# 	},
# 	{
# 		"tier" : "Lowest",
# 		"lowerbound" : -1.000,
# 		"upperbound" : 0.200,
# 		"tier_type" : "company"
# 	},
# 	{
# 		"tier" : "Significantly Below Average",
# 		"lowerbound" : -1.000,
# 		"upperbound" : 20.000,
# 		"tier_type" : "global"
# 	},
# 	{
# 		"tier" : "Negligible",
# 		"lowerbound" : -1.000,
# 		"upperbound" : 5.000,
# 		"tier_type" : "hazard"
# 	},
# 	{
# 		"tier" : "Severe",
# 		"lowerbound" : 75.000,
# 		"upperbound" : 99999999999.000,
# 		"tier_type" : "exposure_percentile"
# 	},
# 	{
# 		"tier" : "Low",
# 		"lowerbound" : 1.000,
# 		"upperbound" : 5.000,
# 		"tier_type" : "exposure_percentile"
# 	},
# 	{
# 		"tier" : "Medium",
# 		"lowerbound" : 5.000,
# 		"upperbound" : 25.000,
# 		"tier_type" : "exposure_percentile"
# 	},
# 	{
# 		"tier" : "High",
# 		"lowerbound" : 25.000,
# 		"upperbound" : 75.000,
# 		"tier_type" : "exposure_percentile"
# 	},
# 	{
# 		"tier" : "Negligible",
# 		"lowerbound" : -1.000,
# 		"upperbound" : 1.000,
# 		"tier_type" : "exposure_percentile"
# 	},
# 	{
# 		"tier" : "Severe - Negative Cash Flow",
# 		"lowerbound" : -99999999999.000,
# 		"upperbound" : -1.000,
# 		"tier_type" : "exposure_percentile"
# 	},
# 	{
# 		"tier" : "Negligible",
# 		"lowerbound" : -1.000,
# 		"upperbound" : 5.000,
# 		"tier_type" : "country"
# 	},
# 	{
# 		"tier" : "Low",
# 		"lowerbound" : 0.010,
# 		"upperbound" : 0.025,
# 		"tier_type" : "exposure"
# 	},
# 	{
# 		"tier" : "High",
# 		"lowerbound" : 0.050,
# 		"upperbound" : 0.100,
# 		"tier_type" : "exposure"
# 	},
# 	{
# 		"tier" : "Medium",
# 		"lowerbound" : 0.025,
# 		"upperbound" : 0.050,
# 		"tier_type" : "exposure"
# 	},
# 	{
# 		"tier" : "Severe",
# 		"lowerbound" : 0.100,
# 		"upperbound" : 99999999999.000,
# 		"tier_type" : "exposure"
# 	},
# 	{
# 		"tier" : "Severe - Negative Cash Flow",
# 		"lowerbound" : -99999999999.000,
# 		"upperbound" : -1.000,
# 		"tier_type" : "exposure"
# 	},
# 	{
# 		"tier" : "Negligible",
# 		"lowerbound" : -1.000,
# 		"upperbound" : 0.010,
# 		"tier_type" : "exposure"
# 	}
# ])
tier_conditions =  pd.read_csv('tier_conditions.csv')

tier_conditions

,tier,lowerbound,upperbound,tier_type
0,Highest,8.000000e-01,1.000000e+00,company
1,High,6.000000e-01,8.000000e-01,company
2,Moderate,4.000000e-01,6.000000e-01,company
3,Low,2.000000e-01,4.000000e-01,company
4,Moderate,5.000000e+00,2.500000e+01,country
5,Significant,2.500000e+01,5.000000e+01,country
6,Leading,5.000000e+01,1.000000e+02,country
7,Below Average,2.000000e+01,4.000000e+01,global
8,Average,4.000000e+01,6.000000e+01,global
9,Above Average,6.000000e+01,8.000000e+01,global
10,Significantly Above Average,8.000000e+01,1.000000e+02,global
11,Moderate,5.000000e+00,2.500000e+01,hazard
12,Significant,2.500000e+01,5.000000e+01,hazard
13,Leading,5.000000e+01,1.000000e+02,hazard
14,Lowest,-1.000000e+00,2.000000e-01,company
15,Significantly Below Average,-1.000000e+00,2.000000e+01,global
16,Negligible,-1.000000e+00,5.000000e+00,hazard
17,Severe,7.500000e+01,1.000000e+11,exposure_percentile
18,Low,1.000000e+00,5.000000e+00,exposure_percentile
19,Medium,5.000000e+00,2.500000e+01,exposure_percentile
20,High,2.500000e+01,7.500000e+01,exposure_percentile
21,Negligible,-1.000000e+00,1.000000e+00,exposure_percentile
22,Severe - Negative Cash Flow,-1.000000e+11,-1.000000e+00,exposure_percentile
23,Negligible,-1.000000e+00,5.000000e+00,country
24,Low,1.000000e-02,2.500000e-02,exposure
25,High,5.000000e-02,1.000000e-01,exposure
26,Medium,2.500000e-02,5.000000e-02,exposure
27,Severe,1.000000e-01,1.000000e+11,exposure
28,Severe - Negative Cash Flow,-1.000000e+11,-1.000000e+00,exposure
29,Negligible,-1.000000e+00,1.000000e-02,exposure

In [103]:
udf_select_country_final[['entity_id',
 'rcp_scenario',
 'physical_impact_year',
 'country_iso3',
 'country_asset_damage_risk',
 'country_contribution_percentage_asset_damage_risk',
 'country_contribution_percentage_high_risk_assets',
 'country_contribution_percentage_productive_capacity_loss',
 'country_high_risk_assets_percentage',
 'country_productive_capacity_loss',
 'percent_of_assets_in_country',
 'overall_asset_damage_risk',
 'overall_productive_capacity_loss',
 'country_contribution_percentage_regional_infrastructure_risk',
 'percentage_local_critical_infrastructure_risk']]

,entity_id,rcp_scenario,physical_impact_year,country_iso3,country_asset_damage_risk,country_contribution_percentage_asset_damage_risk,country_contribution_percentage_high_risk_assets,country_contribution_percentage_productive_capacity_loss,country_high_risk_assets_percentage,country_productive_capacity_loss,percent_of_assets_in_country,overall_asset_damage_risk,overall_productive_capacity_loss,country_contribution_percentage_regional_infrastructure_risk,percentage_local_critical_infrastructure_risk
0,1008128171,RCP2.6,2022,ARE,0.000049,0,0,0,0.000000,0.002724,0.001715,0.001682,0.001052,0,0
1,1008128171,RCP2.6,2022,ARG,0.000049,0,0,0,0.000000,0.000021,0.008576,0.001682,0.001052,1,0
2,1008128171,RCP2.6,2022,AUS,0.003942,43,36,22,0.017153,0.001244,0.183533,0.001682,0.001052,15,49
3,1008128171,RCP2.6,2022,BEL,0.000496,0,0,0,0.000000,0.000105,0.001715,0.001682,0.001052,0,0
4,1008128171,RCP2.6,2022,BFA,0.000045,0,0,1,0.000000,0.002723,0.003431,0.001682,0.001052,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,1008128171,RCP2.6,2100,TWN,0.001177,0,0,0,0.000000,0.000311,0.005146,0.006829,0.002675,1,0
304,1008128171,RCP2.6,2100,TZA,0.000060,0,0,0,0.000000,0.000156,0.027444,0.006829,0.002675,1,0
305,1008128171,RCP2.6,2100,USA,0.002960,17,28,28,0.020583,0.001893,0.394511,0.006829,0.002675,39,19
306,1008128171,RCP2.6,2100,ZAF,0.000113,0,0,0,0.000000,0.000429,0.005146,0.006829,0.002675,0,0
307,1008128171,RCP2.6,2100,ZMB,0.000878,0,0,0,0.000000,0.001728,0.001715,0.006829,0.002675,0,0

In [104]:
def categorize_level(level, tier_conditions,tier_type):
    if pd.isna(level):
        return None
    tier_country = tier_conditions[tier_conditions['tier_type'] == tier_type].iloc[:,:-1].reset_index(drop=True)
    for _, row in tier_country.iterrows():
        if level is None:
            return None
        if row['lowerbound'] < level <= row['upperbound']:
            return row['tier']
    return None

In [105]:
dct_country = tier_conditions[tier_conditions['tier_type']=='country'].sort_values(by ='lowerbound' ).to_dict(orient='list')

# Create bins and labels for pd.cut
country_bins = sorted(set(dct_country['lowerbound'] + dct_country['upperbound']))
country_labels = dct_country['tier']

In [106]:
udf_select_country_final['country_contribution_category_productive_capacity_loss'] = pd.cut(
    udf_select_country_final['country_contribution_percentage_productive_capacity_loss'],
    bins=country_bins,
    labels=country_labels,
    right=True)

udf_select_country_final['country_contribution_category_regional_infrastructure_risk'] = pd.cut(
    udf_select_country_final['country_contribution_percentage_regional_infrastructure_risk'],
    bins=country_bins,
    labels=country_labels,
    right=True)

udf_select_country_final['country_contribution_category_high_risk_assets'] = pd.cut(
    udf_select_country_final['country_contribution_percentage_high_risk_assets'],
    bins=country_bins,
    labels=country_labels,
    right=True)

udf_select_country_final['category_local_critical_infrastructure_risk'] = pd.cut(
    udf_select_country_final['percentage_local_critical_infrastructure_risk'],
    bins=country_bins,
    labels=country_labels,
    right=True)

udf_select_country_final['country_contribution_category_asset_damage_risk'] = pd.cut(
    udf_select_country_final['country_contribution_percentage_asset_damage_risk'],
    bins=country_bins,
    labels=country_labels,
    right=True)

# udf_select_country_final['country_contribution_category_productive_capacity_loss'] = udf_select_country_final['country_contribution_percentage_productive_capacity_loss'].apply(lambda x: categorize_level(x, tier_conditions,'country'))

# udf_select_country_final['country_contribution_category_regional_infrastructure_risk'] = udf_select_country_final['country_contribution_percentage_regional_infrastructure_risk'].apply(lambda x: categorize_level(x, tier_conditions,'country'))

# udf_select_country_final['country_contribution_category_high_risk_assets'] = udf_select_country_final['country_contribution_percentage_high_risk_assets'].apply(lambda x: categorize_level(x, tier_conditions,'country'))

# udf_select_country_final['category_local_critical_infrastructure_risk'] = udf_select_country_final['percentage_local_critical_infrastructure_risk'].apply(lambda x: categorize_level(x, tier_conditions,'country'))

# udf_select_country_final['country_contribution_category_asset_damage_risk'] = udf_select_country_final['country_contribution_percentage_asset_damage_risk'].apply(lambda x: categorize_level(x, tier_conditions,'country'))

## test Code

In [107]:
# sd = udf_select_country_final['country_contribution_percentage_productive_capacity_loss'].copy()
# sd.apply(lambda x: categorize_level(x, tier_conditions,'country')).tolist() == udf_select_country_final['country_contribution_category_productive_capacity_loss'].tolist()

In [108]:
udf_select_country_final.to_csv(f'out/country_calc/{comp_id}_country_risk_full.csv',index =False)
udf_select_country_final.columns

Index(['rcp_scenario', 'clientindustryid', 'entity_id', 'physical_impact_year',
       'country_iso3', 'country_asset_damage_risk',
       'country_productive_capacity_loss',
       'count_assets_with_asset_damage_risk', 'count_assets_with_prodloss',
       'percent_of_assets_in_country', 'total_assets_count',
       'overall_asset_damage_risk', 'overall_productive_capacity_loss',
       'CompanyName', 'count_uninsured', 'count_0_2_pct', 'count_0_5_pct',
       'avg_rei', 'overall_weighted_rei', 'avg_fmi', 'overall_weighted_fmi',
       'country_contribution_percentage_asset_damage_risk',
       'country_contribution_percentage_productive_capacity_loss',
       'country_contribution_percentage_high_risk_assets',
       'country_high_risk_assets_percentage',
       'percentage_local_critical_infrastructure_risk',
       'country_contribution_percentage_regional_infrastructure_risk',
       'country_contribution_category_productive_capacity_loss',
       'country_contribution_category_regional_infrastructure_risk',
       'country_contribution_category_high_risk_assets',
       'category_local_critical_infrastructure_risk',
       'country_contribution_category_asset_damage_risk'],
      dtype='object')

In [109]:
udf_select_country_final1 = udf_select_country_final[["entity_id","rcp_scenario","physical_impact_year","country_iso3","country_asset_damage_risk","country_contribution_percentage_asset_damage_risk","country_contribution_percentage_high_risk_assets","country_contribution_category_asset_damage_risk","country_contribution_category_high_risk_assets","country_contribution_category_productive_capacity_loss","country_contribution_percentage_productive_capacity_loss","country_high_risk_assets_percentage","country_productive_capacity_loss","percent_of_assets_in_country","overall_asset_damage_risk","overall_productive_capacity_loss","country_contribution_percentage_regional_infrastructure_risk","country_contribution_category_regional_infrastructure_risk","percentage_local_critical_infrastructure_risk","category_local_critical_infrastructure_risk"]]

In [112]:
udf_select_country_final1.to_csv(f'out/country_calc/{comp_id}_country_risk.csv',index =False)

### Final Hazard Risk Calculation

In [113]:
def udf_pct_change_direction(x):
    if x == 0:
        return 'No Change'
    elif x < 0:
        return 'Decreasing'
    else:
        return 'Increasing'

In [114]:
df_global_haz = df_full.groupby(['Scenario', 'clientindustryid', 'sustcompanyid', 'Year', 'hazard_type']).agg(
        avg_hazard_risk=('avg_hazard_risk', 'mean'),
        weighted_avg_hazard_risk=('weighted_avg_hazard_risk', 'sum'),
        productive_capacity_loss=('productive_capacity_loss', 'mean'),
        productive_capacity_loss_days=('productive_capacity_loss_days', 'sum'),
        weighted_prodloss=('weighted_prodloss', 'sum'),
        count_assets_with_asset_damage_risk=('count_assets_with_asset_damage_risk', 'sum'),
        count_assets_with_prodloss=('count_assets_with_prodloss', 'sum'),
        total_assets_count=('total_assets_count', 'max')
    ).reset_index()

In [115]:
df_global_haz = df_global_haz.drop('clientindustryid',axis=1)

In [116]:
df_global_all = df_global_haz.rename(columns={'Scenario':'rcp_scenario'}).groupby(['rcp_scenario', 'sustcompanyid', 'Year']).agg(
        # avg_hazard_risk=('avg_hazard_risk', 'sum'),
        overall_asset_damage_risk=('weighted_avg_hazard_risk', 'sum'),
        productive_capacity_loss=('productive_capacity_loss', 'sum'),
        productive_capacity_loss_days=('productive_capacity_loss_days', 'sum'),
        overall_productive_capacity_loss=('weighted_prodloss', 'sum'),
        count_assets_with_asset_damage_risk=('count_assets_with_asset_damage_risk', 'max'),
        count_assets_with_prodloss=('count_assets_with_prodloss', 'max'),
        total_assets_count=('total_assets_count', 'max')
    ).reset_index()

df_global_all = df_global_all.rename(columns = {"rcp_scenario":"Scenario"})

In [117]:
df_global_all

,Scenario,sustcompanyid,Year,overall_asset_damage_risk,productive_capacity_loss,productive_capacity_loss_days,overall_productive_capacity_loss,count_assets_with_asset_damage_risk,count_assets_with_prodloss,total_assets_count
0,RCP2.6,1008128171,2022,0.001682,0.000996,15.989972,0.001052,22,253,583
1,RCP2.6,1008128171,2023,0.001689,0.001002,16.095788,0.001059,22,259,583
2,RCP2.6,1008128171,2025,0.001703,0.001015,16.304663,0.001073,22,267,583
3,RCP2.6,1008128171,2027,0.001714,0.001026,16.479824,0.001085,22,273,583
4,RCP2.6,1008128171,2028,0.001722,0.001034,16.607597,0.001092,22,277,583
5,RCP2.6,1008128171,2030,0.001726,0.001041,16.712856,0.001102,22,284,583
6,RCP2.6,1008128171,2035,0.001759,0.001076,17.272686,0.001134,22,296,583
7,RCP2.6,1008128171,2040,0.001804,0.001123,18.041110,0.001178,22,318,583
8,RCP2.6,1008128171,2045,0.001863,0.001184,19.016727,0.001234,22,336,583
9,RCP2.6,1008128171,2050,0.001949,0.001261,20.255546,0.001297,22,353,583
10,RCP2.6,1008128171,2100,0.006829,0.001902,30.544308,0.002675,24,429,583

In [118]:
df_global_all = df_global_all[['Scenario', 'sustcompanyid', 'Year',
       'overall_asset_damage_risk', 'overall_productive_capacity_loss']]

In [119]:
# df_global_haz.columns

In [120]:
df_global_haz['lagged_weighted_avg_hazard_risk'] = df_global_haz.groupby(['Scenario', 'sustcompanyid', 'hazard_type'])['weighted_avg_hazard_risk'].shift(1)
df_global_haz['lagged_weighted_prodloss'] = df_global_haz.groupby(['Scenario', 'sustcompanyid', 'hazard_type'])['weighted_prodloss'].shift(1)

df_udf_select_hazard_semi_final = df_global_haz.merge(df_global_all.rename(columns = {"rcp_scenario":"Scenario"}), on=['sustcompanyid', 'Scenario', 'Year'])

In [121]:
# df_udf_select_hazard_semi_final = df_udf_select_hazard_semi_final.rename(columns={'clientindustryid_x':'clientindustryid'})
df_udf_select_hazard_semi_final

,Scenario,sustcompanyid,Year,hazard_type,avg_hazard_risk,weighted_avg_hazard_risk,productive_capacity_loss,productive_capacity_loss_days,weighted_prodloss,count_assets_with_asset_damage_risk,count_assets_with_prodloss,total_assets_count,lagged_weighted_avg_hazard_risk,lagged_weighted_prodloss,overall_asset_damage_risk,overall_productive_capacity_loss
0,RCP2.6,1008128171,2022,Coastal Inundation,0.000262,0.000482,0.000089,1.432547,1.280742e-04,3,3,583,NaN,NaN,0.001682,0.001052
1,RCP2.6,1008128171,2022,Cyclone Wind,0.000016,0.000009,0.000002,0.024816,8.553974e-07,0,0,583,NaN,NaN,0.001682,0.001052
2,RCP2.6,1008128171,2022,Extreme Heat,0.000000,0.000000,0.000632,10.150864,5.704011e-04,0,253,583,NaN,NaN,0.001682,0.001052
3,RCP2.6,1008128171,2022,Extreme Wind,0.000049,0.000053,0.000004,0.057140,3.804318e-06,0,0,583,NaN,NaN,0.001682,0.001052
4,RCP2.6,1008128171,2022,Flooding,0.000805,0.000733,0.000139,2.227087,1.244620e-04,22,40,583,NaN,NaN,0.001682,0.001052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,RCP2.6,1008128171,2100,Extreme Wind,0.000070,0.000071,0.000005,0.081507,5.147307e-06,0,1,583,0.000057,0.000004,0.006829,0.002675
84,RCP2.6,1008128171,2100,Flooding,0.000912,0.000877,0.000156,2.508419,1.455864e-04,22,42,583,0.000789,0.000133,0.006829,0.002675
85,RCP2.6,1008128171,2100,Forest Fire,0.000147,0.000240,0.000189,3.034502,3.056991e-04,2,27,583,0.000198,0.000253,0.006829,0.002675
86,RCP2.6,1008128171,2100,Freeze-Thaw,0.000071,0.000230,0.000000,0.000000,0.000000e+00,0,0,583,0.000230,0.000000,0.006829,0.002675
87,RCP2.6,1008128171,2100,Soil Subsidence,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0,0,583,0.000000,0.000000,0.006829,0.002675

In [122]:
df_udf_select_hazard_semi_final['hazard_momentum_direction_asset_damage_risk'] = df_udf_select_hazard_semi_final.apply(
    lambda row: udf_pct_change_direction(row['weighted_avg_hazard_risk'] - row['lagged_weighted_avg_hazard_risk']), axis=1)

df_udf_select_hazard_semi_final['hazard_momentum_direction_productive_capacity_loss'] = df_udf_select_hazard_semi_final.apply(
    lambda row: udf_pct_change_direction(row['weighted_prodloss'] - row['lagged_weighted_prodloss']), axis=1)

In [123]:
dct_hazard = tier_conditions[tier_conditions['tier_type']=='country'].sort_values(by ='lowerbound' ).to_dict(orient='list')

# Create bins and labels for pd.cut
hazard_bins = sorted(set(dct_hazard['lowerbound'] + dct_hazard['upperbound']))
hazard_labels = dct_hazard['tier']
hazard_bins, hazard_labels

([-1.0, 5.0, 25.0, 50.0, 100.0],
 ['Negligible', 'Moderate', 'Significant', 'Leading'])

In [124]:
df_udf_select_hazard_semi_final['hazard_asset_damage_risk'] = df_udf_select_hazard_semi_final['weighted_avg_hazard_risk']
df_udf_select_hazard_semi_final['hazard_contribution_percentage_asset_damage_risk'] = (
    df_udf_select_hazard_semi_final['weighted_avg_hazard_risk'] / df_udf_select_hazard_semi_final['overall_asset_damage_risk'].replace({0: np.nan})
).fillna(0).round(2) * 100


# df_udf_select_hazard_semi_final['hazard_contribution_category_asset_damage_risk'] = df_udf_select_hazard_semi_final['hazard_contribution_percentage_asset_damage_risk'].apply(
#     lambda x: categorize_level(x,tier_conditions, 'hazard'))

df_udf_select_hazard_semi_final['hazard_contribution_percentage_productive_capacity_loss'] = (
    df_udf_select_hazard_semi_final['weighted_prodloss'] / df_udf_select_hazard_semi_final['overall_productive_capacity_loss'].replace({0: np.nan})
).fillna(0).round(2) * 100

# df_udf_select_hazard_semi_final['hazard_contribution_category_productive_capacity_loss'] = df_udf_select_hazard_semi_final['hazard_contribution_percentage_productive_capacity_loss'].apply( 
#     lambda x: categorize_level(x,tier_conditions, 'hazard'))

In [125]:
df_udf_select_hazard_semi_final['hazard_contribution_category_asset_damage_risk'] = pd.cut(
    df_udf_select_hazard_semi_final['hazard_contribution_percentage_asset_damage_risk'],
    bins=hazard_bins,
    labels=hazard_labels,
    right=True)

df_udf_select_hazard_semi_final['hazard_contribution_category_productive_capacity_loss'] = pd.cut(
    df_udf_select_hazard_semi_final['hazard_contribution_percentage_productive_capacity_loss'],
    bins=hazard_bins,
    labels=hazard_labels,
    right=True)

In [126]:
df_udf_select_hazard_semi_final[['Year','hazard_type',
    'hazard_contribution_percentage_productive_capacity_loss', 'hazard_momentum_direction_productive_capacity_loss']][df_udf_select_hazard_semi_final['hazard_type'] == 'Coastal Inundation']

,Year,hazard_type,hazard_contribution_percentage_productive_capacity_loss,hazard_momentum_direction_productive_capacity_loss
0,2022,Coastal Inundation,12.0,Increasing
8,2023,Coastal Inundation,12.0,Increasing
16,2025,Coastal Inundation,12.0,Increasing
24,2027,Coastal Inundation,12.0,Increasing
32,2028,Coastal Inundation,12.0,Increasing
40,2030,Coastal Inundation,12.0,No Change
48,2035,Coastal Inundation,13.0,Increasing
56,2040,Coastal Inundation,13.0,Increasing
64,2045,Coastal Inundation,13.0,Increasing
72,2050,Coastal Inundation,14.0,Increasing
80,2100,Coastal Inundation,49.0,Increasing

In [127]:
df_udf_select_hazard_semi_final['hazard_productive_capacity_loss'] = df_udf_select_hazard_semi_final['weighted_prodloss']
df_udf_select_hazard_semi_final = df_udf_select_hazard_semi_final.rename(columns={
    'sustcompanyid': 'entity_id',
    'Scenario': 'rcp_scenario',
    'Year': 'physical_impact_year',
    'overall_asset_damage_risk': 'overall_asset_damage_risk',
    'overall_productive_capacity_loss': 'overall_productive_capacity_loss'
})

In [128]:
df_udf_select_hazard_semi_final[df_udf_select_hazard_semi_final['hazard_type']=='Coastal Inundation']

,rcp_scenario,entity_id,physical_impact_year,hazard_type,avg_hazard_risk,weighted_avg_hazard_risk,productive_capacity_loss,productive_capacity_loss_days,weighted_prodloss,count_assets_with_asset_damage_risk,...,overall_asset_damage_risk,overall_productive_capacity_loss,hazard_momentum_direction_asset_damage_risk,hazard_momentum_direction_productive_capacity_loss,hazard_asset_damage_risk,hazard_contribution_percentage_asset_damage_risk,hazard_contribution_percentage_productive_capacity_loss,hazard_contribution_category_asset_damage_risk,hazard_contribution_category_productive_capacity_loss,hazard_productive_capacity_loss
0,RCP2.6,1008128171,2022,Coastal Inundation,0.000262,0.000482,0.000089,1.432547,0.000128,3,...,0.001682,0.001052,Increasing,Increasing,0.000482,29.0,12.0,Significant,Moderate,0.000128
8,RCP2.6,1008128171,2023,Coastal Inundation,0.000270,0.000485,0.000092,1.473316,0.000129,3,...,0.001689,0.001059,Increasing,Increasing,0.000485,29.0,12.0,Significant,Moderate,0.000129
16,RCP2.6,1008128171,2025,Coastal Inundation,0.000284,0.000491,0.000097,1.552489,0.000131,3,...,0.001703,0.001073,Increasing,Increasing,0.000491,29.0,12.0,Significant,Moderate,0.000131
24,RCP2.6,1008128171,2027,Coastal Inundation,0.000296,0.000496,0.000100,1.611864,0.000133,3,...,0.001714,0.001085,Increasing,Increasing,0.000496,29.0,12.0,Significant,Moderate,0.000133
32,RCP2.6,1008128171,2028,Coastal Inundation,0.000309,0.000502,0.000105,1.683504,0.000135,3,...,0.001722,0.001092,Increasing,Increasing,0.000502,29.0,12.0,Significant,Moderate,0.000135
40,RCP2.6,1008128171,2030,Coastal Inundation,0.000309,0.000502,0.000105,1.683504,0.000135,3,...,0.001726,0.001102,No Change,No Change,0.000502,29.0,12.0,Significant,Moderate,0.000135
48,RCP2.6,1008128171,2035,Coastal Inundation,0.000366,0.000525,0.000123,1.974123,0.000142,3,...,0.001759,0.001134,Increasing,Increasing,0.000525,30.0,13.0,Significant,Moderate,0.000142
56,RCP2.6,1008128171,2040,Coastal Inundation,0.000443,0.000558,0.000146,2.350538,0.000152,3,...,0.001804,0.001178,Increasing,Increasing,0.000558,31.0,13.0,Significant,Moderate,0.000152
64,RCP2.6,1008128171,2045,Coastal Inundation,0.000538,0.000598,0.000173,2.785016,0.000163,3,...,0.001863,0.001234,Increasing,Increasing,0.000598,32.0,13.0,Significant,Moderate,0.000163
72,RCP2.6,1008128171,2050,Coastal Inundation,0.000693,0.000664,0.000213,3.422876,0.000180,3,...,0.001949,0.001297,Increasing,Increasing,0.000664,34.0,14.0,Significant,Moderate,0.000180
80,RCP2.6,1008128171,2100,Coastal Inundation,0.002507,0.005398,0.000616,9.896876,0.001319,24,...,0.006829,0.002675,Increasing,Increasing,0.005398,79.0,49.0,Leading,Significant,0.001319

In [129]:
df_udf_select_hazard_semi_final.columns

Index(['rcp_scenario', 'entity_id', 'physical_impact_year', 'hazard_type',
       'avg_hazard_risk', 'weighted_avg_hazard_risk',
       'productive_capacity_loss', 'productive_capacity_loss_days',
       'weighted_prodloss', 'count_assets_with_asset_damage_risk',
       'count_assets_with_prodloss', 'total_assets_count',
       'lagged_weighted_avg_hazard_risk', 'lagged_weighted_prodloss',
       'overall_asset_damage_risk', 'overall_productive_capacity_loss',
       'hazard_momentum_direction_asset_damage_risk',
       'hazard_momentum_direction_productive_capacity_loss',
       'hazard_asset_damage_risk',
       'hazard_contribution_percentage_asset_damage_risk',
       'hazard_contribution_percentage_productive_capacity_loss',
       'hazard_contribution_category_asset_damage_risk',
       'hazard_contribution_category_productive_capacity_loss',
       'hazard_productive_capacity_loss'],
      dtype='object')

In [130]:
df_udf_select_hazard_final = df_udf_select_hazard_semi_final[["entity_id","rcp_scenario","physical_impact_year",
"hazard_type","hazard_asset_damage_risk","hazard_contribution_category_asset_damage_risk",
"hazard_contribution_category_productive_capacity_loss","hazard_contribution_percentage_asset_damage_risk",
"hazard_contribution_percentage_productive_capacity_loss","hazard_momentum_direction_asset_damage_risk",
"hazard_momentum_direction_productive_capacity_loss",
"hazard_productive_capacity_loss","overall_asset_damage_risk","overall_productive_capacity_loss"]]

In [131]:
df_udf_select_hazard_final.head()

,entity_id,rcp_scenario,physical_impact_year,hazard_type,hazard_asset_damage_risk,hazard_contribution_category_asset_damage_risk,hazard_contribution_category_productive_capacity_loss,hazard_contribution_percentage_asset_damage_risk,hazard_contribution_percentage_productive_capacity_loss,hazard_momentum_direction_asset_damage_risk,hazard_momentum_direction_productive_capacity_loss,hazard_productive_capacity_loss,overall_asset_damage_risk,overall_productive_capacity_loss
0,1008128171,RCP2.6,2022,Coastal Inundation,0.000482,Significant,Moderate,29.0,12.0,Increasing,Increasing,1.280742e-04,0.001682,0.001052
1,1008128171,RCP2.6,2022,Cyclone Wind,0.000009,Negligible,Negligible,1.0,0.0,Increasing,Increasing,8.553974e-07,0.001682,0.001052
2,1008128171,RCP2.6,2022,Extreme Heat,0.000000,Negligible,Leading,0.0,54.0,Increasing,Increasing,5.704011e-04,0.001682,0.001052
3,1008128171,RCP2.6,2022,Extreme Wind,0.000053,Negligible,Negligible,3.0,0.0,Increasing,Increasing,3.804318e-06,0.001682,0.001052
4,1008128171,RCP2.6,2022,Flooding,0.000733,Significant,Moderate,44.0,12.0,Increasing,Increasing,1.244620e-04,0.001682,0.001052

In [132]:
df_udf_select_hazard_final.to_csv(f'out/hazard_calc/{comp_id}_hazard_risk_final.csv', index=False)

# Alternate Way to calculate hazard_Risk_Final

In [133]:
global_haz_df = global_haz.drop('clientindustryid',axis=1).rename(columns={'Scenario':'rcp_scenario'})

In [134]:
global_all_df = global_all[['rcp_scenario', 'sustcompanyid', 'Year',
       'overall_asset_damage_risk', 'overall_productive_capacity_loss']]
global_all_df

,rcp_scenario,sustcompanyid,Year,overall_asset_damage_risk,overall_productive_capacity_loss
0,RCP2.6,1008128171,2022,0.001682,0.001052
1,RCP2.6,1008128171,2023,0.001689,0.001059
2,RCP2.6,1008128171,2027,0.001714,0.001085
3,RCP2.6,1008128171,2028,0.001722,0.001092
4,RCP2.6,1008128171,2030,0.001726,0.001102
5,RCP2.6,1008128171,2050,0.001949,0.001297
6,RCP2.6,1008128171,2100,0.006829,0.002675

In [135]:
global_haz_df['lagged_weighted_avg_hazard_risk'] = global_haz_df.groupby(['rcp_scenario', 'sustcompanyid', 'hazard_type'])['weighted_avg_hazard_risk'].shift(1)
global_haz_df['lagged_weighted_prodloss'] = global_haz_df.groupby(['rcp_scenario', 'sustcompanyid', 'hazard_type'])['weighted_prodloss'].shift(1)

df_final = global_haz_df.merge(global_all_df, on=['sustcompanyid', 'rcp_scenario', 'Year'])

In [136]:
dct_hazard = tier_conditions[tier_conditions['tier_type']=='country'].sort_values(by ='lowerbound' ).to_dict(orient='list')

# Create bins and labels for pd.cut
hazard_bins = sorted(set(dct_hazard['lowerbound'] + dct_hazard['upperbound']))
hazard_labels = dct_hazard['tier']
hazard_bins, hazard_labels

([-1.0, 5.0, 25.0, 50.0, 100.0],
 ['Negligible', 'Moderate', 'Significant', 'Leading'])

In [137]:
df_final['hazard_momentum_direction_asset_damage_risk'] = df_final.apply(
    lambda row: udf_pct_change_direction(row['weighted_avg_hazard_risk'] - row['lagged_weighted_avg_hazard_risk']), axis=1)

df_final['hazard_momentum_direction_productive_capacity_loss'] = df_final.apply(
    lambda row: udf_pct_change_direction(row['weighted_prodloss'] - row['lagged_weighted_prodloss']), axis=1)
df_final['hazard_asset_damage_risk'] = df_final['weighted_avg_hazard_risk']
df_final['hazard_contribution_percentage_asset_damage_risk'] = (
    df_final['weighted_avg_hazard_risk'] / df_final['overall_asset_damage_risk'].replace({0: np.nan})
).fillna(0).round(2) * 100

# df_final['hazard_contribution_category_asset_damage_risk'] = df_final['hazard_contribution_percentage_asset_damage_risk'].apply(
#     lambda x: categorize_level(x,tier_conditions, 'hazard'))

df_final['hazard_contribution_percentage_productive_capacity_loss'] = (
    df_final['weighted_prodloss'] / df_final['overall_productive_capacity_loss'].replace({0: np.nan})
).fillna(0).round(2) * 100

# df_final['hazard_contribution_category_productive_capacity_loss'] = df_final['hazard_contribution_percentage_productive_capacity_loss'].apply( lambda x: categorize_level(x,tier_conditions, 'hazard'))

In [138]:
df_final['hazard_contribution_category_asset_damage_risk'] = pd.cut(
    df_final['hazard_contribution_percentage_asset_damage_risk'],
    bins=hazard_bins,
    labels=hazard_labels,
    right=True)

df_final['hazard_contribution_category_productive_capacity_loss'] = pd.cut(
    df_final['hazard_contribution_percentage_productive_capacity_loss'],
    bins=hazard_bins,
    labels=hazard_labels,
    right=True)

In [139]:
df_final['hazard_productive_capacity_loss'] = df_final['weighted_prodloss']
df_final = df_final.rename(columns={
    'sustcompanyid': 'entity_id',
    'Scenario': 'rcp_scenario',
    'Year': 'physical_impact_year',
    'overall_asset_damage_risk': 'overall_asset_damage_risk',
    'overall_productive_capacity_loss': 'overall_productive_capacity_loss'
})

In [140]:
df_hazard_final = df_final[["entity_id","rcp_scenario","physical_impact_year",
"hazard_type","hazard_asset_damage_risk","hazard_contribution_category_asset_damage_risk",
"hazard_contribution_category_productive_capacity_loss","hazard_contribution_percentage_asset_damage_risk",
"hazard_contribution_percentage_productive_capacity_loss","hazard_momentum_direction_asset_damage_risk",
"hazard_momentum_direction_productive_capacity_loss",
"hazard_productive_capacity_loss","overall_asset_damage_risk","overall_productive_capacity_loss"]]

In [141]:
df_hazard_final.to_csv(f'out/hazard_calc/{comp_id}_hazard_risk_final_alternate.csv', index=False)

# Global Risk calculation

## Create regional_infrastructure_risk DataFrame

In [142]:
global_country['clientindustryid'] = global_country['clientindustryid'].astype(int)

In [143]:
rei_df = rei_df.rename(columns = { 'Scenario': 'rcp_scenario',})

In [144]:
global_country.columns

Index(['rcp_scenario', 'clientindustryid', 'sustcompanyid', 'Year', 'Country',
       'avg_hazard_risk', 'productive_capacity_loss',
       'count_assets_with_asset_damage_risk', 'count_assets_with_prodloss',
       'percent_of_assets_in_country', 'total_assets_count'],
      dtype='object')

In [145]:
merged_df = rei_df.merge(
    global_country,
    on=['sustcompanyid', 'Country', 'Year', 'rcp_scenario']
)

In [146]:
merged_df.head()

,rcp_scenario,sustcompanyid,CompanyName,Country,Year,REI,clientindustryid,avg_hazard_risk,productive_capacity_loss,count_assets_with_asset_damage_risk,count_assets_with_prodloss,percent_of_assets_in_country,total_assets_count
0,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2022,0.005404,151019,0.000049,0.002724,0,1,0.001715,583
1,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2023,0.005404,151019,0.000049,0.002724,0,1,0.001715,583
2,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2025,0.005404,151019,0.000050,0.002724,0,1,0.001715,583
3,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2027,0.005404,151019,0.000050,0.002724,0,1,0.001715,583
4,RCP2.6,1008128171,Barrick Gold Corp.,ARE,2028,0.005404,151019,0.000051,0.002724,0,1,0.001715,583

In [147]:
grouped_df = merged_df.groupby(['sustcompanyid', 'rcp_scenario', 'Year', 'clientindustryid']).agg(
    overall_regional_infrastructure_risk=('REI', lambda x: (x * merged_df['percent_of_assets_in_country']).sum())
).reset_index()

In [148]:
grouped_df

,sustcompanyid,rcp_scenario,Year,clientindustryid,overall_regional_infrastructure_risk
0,1008128171,RCP2.6,2022,151019,0.002060
1,1008128171,RCP2.6,2023,151019,0.002065
2,1008128171,RCP2.6,2025,151019,0.002085
3,1008128171,RCP2.6,2027,151019,0.002108
4,1008128171,RCP2.6,2028,151019,0.002114
5,1008128171,RCP2.6,2030,151019,0.002140
6,1008128171,RCP2.6,2035,151019,0.002203
7,1008128171,RCP2.6,2040,151019,0.002278
8,1008128171,RCP2.6,2045,151019,0.002362
9,1008128171,RCP2.6,2050,151019,0.002457
10,1008128171,RCP2.6,2100,151019,0.003790

# AGGREGATION which should be Done after processing all Companies data
 #### Calculate percentiles
grouped_df['industry_percentile_regional_infrastructure_risk'] = grouped_df.groupby(['scenario_code', 'year'])['overall_regional_infrastructure_risk'].rank(pct=True) * 100
grouped_df['overall_percentile_regional_infrastructure_risk'] = grouped_df.groupby(['scenario_code', 'year', 'clientindustryid'])['overall_regional_infrastructure_risk'].rank(pct=True) * 100

#### Convert percentiles to integers
grouped_df['industry_percentile_regional_infrastructure_risk'] = grouped_df['industry_percentile_regional_infrastructure_risk'].astype(int)
grouped_df['overall_percentile_regional_infrastructure_risk'] = grouped_df['overall_percentile_regional_infrastructure_risk'].astype(int)

#### Apply the custom risk level computation function
grouped_df['industry_category_regional_infrastructure_risk'] = grouped_df['industry_percentile_regional_infrastructure_risk'].apply(lambda x: udf_compute_risk_level(x, 'global'))
grouped_df['overall_category_regional_infrastructure_risk'] = grouped_df['overall_percentile_regional_infrastructure_risk'].apply(lambda x: udf_compute_risk_level(x, 'global'))

#### xdi_processing.udf_select_count() Calculation
select
		c.entity_name,
		c.entity_id,
		c.scenario_code,
		c.year as cnt_year,
		sum(c.count_uninsured) as high_risk_assets_count
    from xdi_input.counts c
	inner join (select distinct year as import_year from xdi_input.import_years
				where active=true and table_name='global') df on c.year = df.import_year
    where c.fl_deleted is distinct from true
    group by c.entity_id, c.entity_name, c.scenario_co 
    `de,c.year;

In [149]:
udf_select_count = counts_df.groupby(['sustcompanyid','CompanyName','rcp_scenario','Year'], as_index=False).agg(
high_risk_assets_count = ('count_uninsured' , 'sum')
)
udf_select_count = udf_select_count.rename(columns = {
    'sustcompanyid': 'entity_id', 'Year' :'physical_impact_year'
})
udf_select_count

,entity_id,CompanyName,rcp_scenario,physical_impact_year,high_risk_assets_count
0,1008128171,Barrick Gold Corp.,RCP2.6,2022,28
1,1008128171,Barrick Gold Corp.,RCP2.6,2023,28
2,1008128171,Barrick Gold Corp.,RCP2.6,2025,28
3,1008128171,Barrick Gold Corp.,RCP2.6,2027,28
4,1008128171,Barrick Gold Corp.,RCP2.6,2028,28
5,1008128171,Barrick Gold Corp.,RCP2.6,2030,28
6,1008128171,Barrick Gold Corp.,RCP2.6,2035,28
7,1008128171,Barrick Gold Corp.,RCP2.6,2040,28
8,1008128171,Barrick Gold Corp.,RCP2.6,2045,28
9,1008128171,Barrick Gold Corp.,RCP2.6,2050,28
10,1008128171,Barrick Gold Corp.,RCP2.6,2100,43

In [150]:
df_temp = udf_select_country_final.merge(udf_select_country_final.groupby(['rcp_scenario', 'clientindustryid', 'entity_id', 'physical_impact_year'], as_index=False).agg(high_risk_assets_count=('count_uninsured','sum')), on= ['rcp_scenario', 'entity_id','clientindustryid', 'physical_impact_year'] )

In [151]:
# coalesce(round((cnt.high_risk_assets_count::numeric / nullif(ga.total_assets_count, 0)) *100, 0),0) as overall_high_risk_assets_percentage,

df_temp['overall_high_risk_assets_percentage'] = (df_temp['high_risk_assets_count']/ df_temp['total_assets_count'].replace(0, pd.NA) * 100).round(0).fillna(0)

In [152]:
global_semi = df_temp.groupby(['rcp_scenario', 'entity_id', 'physical_impact_year'],as_index=False).agg(
    high_risk_assets_count = ('high_risk_assets_count', 'max'),
    overall_asset_damage_risk = ('overall_asset_damage_risk', 'max'),
    overall_high_risk_assets_percentage = ('overall_high_risk_assets_percentage', 'max'),
    overall_productive_capacity_loss = ('overall_productive_capacity_loss', 'max'),
    overall_regional_infrastructure_risk = ('overall_weighted_rei', 'max'),
    overall_local_critical_infrastructure_risk = ('overall_weighted_fmi', 'max') )
global_semi

,rcp_scenario,entity_id,physical_impact_year,high_risk_assets_count,overall_asset_damage_risk,overall_high_risk_assets_percentage,overall_productive_capacity_loss,overall_regional_infrastructure_risk,overall_local_critical_infrastructure_risk
0,RCP2.6,1008128171,2022,28,0.001682,5.0,0.001052,0.002060,0.003771
1,RCP2.6,1008128171,2023,28,0.001689,5.0,0.001059,0.002065,0.003811
2,RCP2.6,1008128171,2027,28,0.001714,5.0,0.001085,0.002108,0.003975
3,RCP2.6,1008128171,2028,28,0.001722,5.0,0.001092,0.002114,0.004016
4,RCP2.6,1008128171,2030,28,0.001726,5.0,0.001102,0.002140,0.004097
5,RCP2.6,1008128171,2050,28,0.001949,5.0,0.001297,0.002457,0.005841
6,RCP2.6,1008128171,2100,43,0.006829,7.0,0.002675,0.003790,0.011719

## Note:
### overall_regional_infrastructure_risk = overall_weighted_rei
### overall_local_critical_infrastructure_risk = overall_weighted_fmi

In [153]:
df_temp.columns

Index(['rcp_scenario', 'clientindustryid', 'entity_id', 'physical_impact_year',
       'country_iso3', 'country_asset_damage_risk',
       'country_productive_capacity_loss',
       'count_assets_with_asset_damage_risk', 'count_assets_with_prodloss',
       'percent_of_assets_in_country', 'total_assets_count',
       'overall_asset_damage_risk', 'overall_productive_capacity_loss',
       'CompanyName', 'count_uninsured', 'count_0_2_pct', 'count_0_5_pct',
       'avg_rei', 'overall_weighted_rei', 'avg_fmi', 'overall_weighted_fmi',
       'country_contribution_percentage_asset_damage_risk',
       'country_contribution_percentage_productive_capacity_loss',
       'country_contribution_percentage_high_risk_assets',
       'country_high_risk_assets_percentage',
       'percentage_local_critical_infrastructure_risk',
       'country_contribution_percentage_regional_infrastructure_risk',
       'country_contribution_category_productive_capacity_loss',
       'country_contribution_category_regional_infrastructure_risk',
       'country_contribution_category_high_risk_assets',
       'category_local_critical_infrastructure_risk',
       'country_contribution_category_asset_damage_risk',
       'high_risk_assets_count', 'overall_high_risk_assets_percentage'],
      dtype='object')

In [154]:
udf_select_country_final.columns

Index(['rcp_scenario', 'clientindustryid', 'entity_id', 'physical_impact_year',
       'country_iso3', 'country_asset_damage_risk',
       'country_productive_capacity_loss',
       'count_assets_with_asset_damage_risk', 'count_assets_with_prodloss',
       'percent_of_assets_in_country', 'total_assets_count',
       'overall_asset_damage_risk', 'overall_productive_capacity_loss',
       'CompanyName', 'count_uninsured', 'count_0_2_pct', 'count_0_5_pct',
       'avg_rei', 'overall_weighted_rei', 'avg_fmi', 'overall_weighted_fmi',
       'country_contribution_percentage_asset_damage_risk',
       'country_contribution_percentage_productive_capacity_loss',
       'country_contribution_percentage_high_risk_assets',
       'country_high_risk_assets_percentage',
       'percentage_local_critical_infrastructure_risk',
       'country_contribution_percentage_regional_infrastructure_risk',
       'country_contribution_category_productive_capacity_loss',
       'country_contribution_category_regional_infrastructure_risk',
       'country_contribution_category_high_risk_assets',
       'category_local_critical_infrastructure_risk',
       'country_contribution_category_asset_damage_risk'],
      dtype='object')

In [155]:
top_country = udf_select_country_final[['entity_id', 'rcp_scenario', 'physical_impact_year','country_iso3','country_contribution_percentage_asset_damage_risk','country_contribution_percentage_high_risk_assets','country_contribution_percentage_productive_capacity_loss','country_contribution_percentage_regional_infrastructure_risk','percentage_local_critical_infrastructure_risk']].copy()

In [156]:
# Compute the maximum values for each percentage column within the specified partitions
top_country['max_asset_damage_risk'] = top_country.groupby(['entity_id', 'rcp_scenario', 'physical_impact_year'])['country_contribution_percentage_asset_damage_risk'].transform('max')
top_country['max_high_risk_assets'] = top_country.groupby(['entity_id', 'rcp_scenario', 'physical_impact_year'])['country_contribution_percentage_high_risk_assets'].transform('max')
top_country['max_productive_capacity_loss'] = top_country.groupby(['entity_id', 'rcp_scenario', 'physical_impact_year'])['country_contribution_percentage_productive_capacity_loss'].transform('max')
top_country['max_regional_infrastructure_risk'] = top_country.groupby(['entity_id', 'rcp_scenario', 'physical_impact_year'])['country_contribution_percentage_regional_infrastructure_risk'].transform('max')
top_country['max_local_critical_infrastructure_risk'] = top_country.groupby(['entity_id', 'rcp_scenario', 'physical_impact_year'])['percentage_local_critical_infrastructure_risk'].transform('max')

#### Top Countries with respect to Datapoints

In [157]:
# Use numpy.where to conditionally select the country_iso3 based on the maximum values
top_country['top_country_contributor_for_asset_damage_risk'] = np.where(
    top_country['country_contribution_percentage_asset_damage_risk'] == top_country['max_asset_damage_risk'],
    top_country['country_iso3'], 
    np.nan
)

top_country['top_country_contributor_for_high_risk_assets'] = np.where(
    top_country['country_contribution_percentage_high_risk_assets'] == top_country['max_high_risk_assets'],
    top_country['country_iso3'], 
    np.nan
)

top_country['top_country_contributor_for_productive_capacity_loss'] = np.where(
    top_country['country_contribution_percentage_productive_capacity_loss'] == top_country['max_productive_capacity_loss'],
    top_country['country_iso3'], 
    np.nan
)

top_country['top_country_contributor_for_regional_risk'] = np.where(
    top_country['country_contribution_percentage_regional_infrastructure_risk'] == top_country['max_regional_infrastructure_risk'],
    top_country['country_iso3'], 
    np.nan
)

top_country['top_country_contributor_for_local_critical_infrastructure'] = np.where(
    top_country['percentage_local_critical_infrastructure_risk'].fillna(-1) == top_country['max_local_critical_infrastructure_risk'],
    top_country['country_iso3'], 
    np.nan
)

### Top Country for Global Calculation

In [158]:
# Aggregate the results by entity_id, rcp_scenario, and physical_impact_year
top_country_global = top_country.groupby(['entity_id', 'rcp_scenario', 'physical_impact_year']).agg(
    top_country_contributor_for_asset_damage_risk=('top_country_contributor_for_asset_damage_risk', 'first'),
    top_country_contributor_for_high_risk_assets=('top_country_contributor_for_high_risk_assets', 'first'),
    top_country_contributor_for_productive_capacity_loss=('top_country_contributor_for_productive_capacity_loss', 'first'),
    top_country_contributor_for_regional_risk=('top_country_contributor_for_regional_risk', 'first'),
    top_country_contributor_for_local_critical_infrastructure=('top_country_contributor_for_local_critical_infrastructure', 'first')
).reset_index()
top_country_global

,entity_id,rcp_scenario,physical_impact_year,top_country_contributor_for_asset_damage_risk,top_country_contributor_for_high_risk_assets,top_country_contributor_for_productive_capacity_loss,top_country_contributor_for_regional_risk,top_country_contributor_for_local_critical_infrastructure
0,1008128171,RCP2.6,2022,AUS,AUS,USA,USA,AUS
1,1008128171,RCP2.6,2023,AUS,AUS,USA,USA,AUS
2,1008128171,RCP2.6,2027,AUS,AUS,USA,USA,AUS
3,1008128171,RCP2.6,2028,AUS,AUS,USA,USA,AUS
4,1008128171,RCP2.6,2030,AUS,AUS,USA,USA,AUS
5,1008128171,RCP2.6,2050,AUS,AUS,USA,USA,AUS
6,1008128171,RCP2.6,2100,AUS,AUS,AUS,USA,AUS

In [159]:
# Compute the maximum values for each percentage column within the specified partitions
hazard_risk = df_hazard_final.copy()

hazard_risk['max_value1'] = hazard_risk.groupby(['entity_id', 'rcp_scenario', 'physical_impact_year'])['hazard_contribution_percentage_productive_capacity_loss'].transform('max')
hazard_risk['max_value2'] = hazard_risk.groupby(['entity_id', 'rcp_scenario', 'physical_impact_year'])['hazard_contribution_percentage_asset_damage_risk'].transform('max')

In [160]:
hazard_risk['top_hazard_contributor_for_productive_capacity_loss'] = np.where(
    hazard_risk['hazard_contribution_percentage_productive_capacity_loss'] == hazard_risk['max_value1'],
    hazard_risk['hazard_type'], 
    np.nan
)

hazard_risk['top_hazard_contributor_for_asset_damage_risk'] = np.where(
    hazard_risk['hazard_contribution_percentage_asset_damage_risk'] == hazard_risk['max_value2'],
    hazard_risk['hazard_type'], 
    np.nan
)

In [161]:
top_hazard_global = hazard_risk[['entity_id', 'rcp_scenario', 'physical_impact_year','top_hazard_contributor_for_productive_capacity_loss','top_hazard_contributor_for_asset_damage_risk']].groupby(['entity_id', 'rcp_scenario', 'physical_impact_year'],as_index=False).agg(
    top_hazard_contributor_for_asset_damage_risk = ('top_hazard_contributor_for_asset_damage_risk','first'),
    top_hazard_contributor_for_productive_capacity_loss = ('top_hazard_contributor_for_productive_capacity_loss', 'first')
)

In [162]:
top_hazard_global

,entity_id,rcp_scenario,physical_impact_year,top_hazard_contributor_for_asset_damage_risk,top_hazard_contributor_for_productive_capacity_loss
0,1008128171,RCP2.6,2022,Flooding,Extreme Heat
1,1008128171,RCP2.6,2023,Flooding,Extreme Heat
2,1008128171,RCP2.6,2027,Flooding,Extreme Heat
3,1008128171,RCP2.6,2028,Flooding,Extreme Heat
4,1008128171,RCP2.6,2030,Flooding,Extreme Heat
5,1008128171,RCP2.6,2050,Flooding,Extreme Heat
6,1008128171,RCP2.6,2100,Coastal Inundation,Coastal Inundation

In [163]:
top_hazard_country_global = top_hazard_global.merge(top_country_global, on = ['entity_id', 'rcp_scenario', 'physical_impact_year'])
top_hazard_country_global.head()

,entity_id,rcp_scenario,physical_impact_year,top_hazard_contributor_for_asset_damage_risk,top_hazard_contributor_for_productive_capacity_loss,top_country_contributor_for_asset_damage_risk,top_country_contributor_for_high_risk_assets,top_country_contributor_for_productive_capacity_loss,top_country_contributor_for_regional_risk,top_country_contributor_for_local_critical_infrastructure
0,1008128171,RCP2.6,2022,Flooding,Extreme Heat,AUS,AUS,USA,USA,AUS
1,1008128171,RCP2.6,2023,Flooding,Extreme Heat,AUS,AUS,USA,USA,AUS
2,1008128171,RCP2.6,2027,Flooding,Extreme Heat,AUS,AUS,USA,USA,AUS
3,1008128171,RCP2.6,2028,Flooding,Extreme Heat,AUS,AUS,USA,USA,AUS
4,1008128171,RCP2.6,2030,Flooding,Extreme Heat,AUS,AUS,USA,USA,AUS

In [164]:
# prod_loss_days = df_full.groupby(['Scenario', 'sustcompanyid', 'Year'], as_index=False).agg(
#     overall_productive_capacity_loss_days = ("weighted_productive_capacity_loss_days","sum")
# ).rename(columns = { 
#     'Scenario': 'rcp_scenario', 'sustcompanyid' : 'entity_id', 'Year' : "physical_impact_year"
# })


prod_loss_days = global_all_full [['rcp_scenario','clientindustryid', 'sustcompanyid', 'Year', 'overall_productive_capacity_loss_days']].rename(columns = { 
    'Scenario': 'rcp_scenario', 'sustcompanyid' : 'entity_id', 'Year' : "physical_impact_year"
})

In [165]:
global_semi_df = global_semi.merge(top_hazard_country_global, on=['entity_id', 'rcp_scenario', 'physical_impact_year'])\
.merge(prod_loss_days,on=['entity_id', 'rcp_scenario', 'physical_impact_year'])\
.merge(df_temp[['entity_id', 'total_assets_count']],on='entity_id')

In [166]:
global_semi_df

,rcp_scenario,entity_id,physical_impact_year,high_risk_assets_count,overall_asset_damage_risk,overall_high_risk_assets_percentage,overall_productive_capacity_loss,overall_regional_infrastructure_risk,overall_local_critical_infrastructure_risk,top_hazard_contributor_for_asset_damage_risk,top_hazard_contributor_for_productive_capacity_loss,top_country_contributor_for_asset_damage_risk,top_country_contributor_for_high_risk_assets,top_country_contributor_for_productive_capacity_loss,top_country_contributor_for_regional_risk,top_country_contributor_for_local_critical_infrastructure,clientindustryid,overall_productive_capacity_loss_days,total_assets_count
0,RCP2.6,1008128171,2022,28,0.001682,5.0,0.001052,0.00206,0.003771,Flooding,Extreme Heat,AUS,AUS,USA,USA,AUS,151019,9322.153909,583
1,RCP2.6,1008128171,2022,28,0.001682,5.0,0.001052,0.00206,0.003771,Flooding,Extreme Heat,AUS,AUS,USA,USA,AUS,151019,9322.153909,583
2,RCP2.6,1008128171,2022,28,0.001682,5.0,0.001052,0.00206,0.003771,Flooding,Extreme Heat,AUS,AUS,USA,USA,AUS,151019,9322.153909,583
3,RCP2.6,1008128171,2022,28,0.001682,5.0,0.001052,0.00206,0.003771,Flooding,Extreme Heat,AUS,AUS,USA,USA,AUS,151019,9322.153909,583
4,RCP2.6,1008128171,2022,28,0.001682,5.0,0.001052,0.00206,0.003771,Flooding,Extreme Heat,AUS,AUS,USA,USA,AUS,151019,9322.153909,583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2151,RCP2.6,1008128171,2100,43,0.006829,7.0,0.002675,0.00379,0.011719,Coastal Inundation,Coastal Inundation,AUS,AUS,AUS,USA,AUS,151019,17807.331418,583
2152,RCP2.6,1008128171,2100,43,0.006829,7.0,0.002675,0.00379,0.011719,Coastal Inundation,Coastal Inundation,AUS,AUS,AUS,USA,AUS,151019,17807.331418,583
2153,RCP2.6,1008128171,2100,43,0.006829,7.0,0.002675,0.00379,0.011719,Coastal Inundation,Coastal Inundation,AUS,AUS,AUS,USA,AUS,151019,17807.331418,583
2154,RCP2.6,1008128171,2100,43,0.006829,7.0,0.002675,0.00379,0.011719,Coastal Inundation,Coastal Inundation,AUS,AUS,AUS,USA,AUS,151019,17807.331418,583
2155,RCP2.6,1008128171,2100,43,0.006829,7.0,0.002675,0.00379,0.011719,Coastal Inundation,Coastal Inundation,AUS,AUS,AUS,USA,AUS,151019,17807.331418,583

In [167]:
global_semi_df.to_csv(f'{comp_id}_global_temp.csv', index=False)

In [168]:
global_semi_df.columns

Index(['rcp_scenario', 'entity_id', 'physical_impact_year',
       'high_risk_assets_count', 'overall_asset_damage_risk',
       'overall_high_risk_assets_percentage',
       'overall_productive_capacity_loss',
       'overall_regional_infrastructure_risk',
       'overall_local_critical_infrastructure_risk',
       'top_hazard_contributor_for_asset_damage_risk',
       'top_hazard_contributor_for_productive_capacity_loss',
       'top_country_contributor_for_asset_damage_risk',
       'top_country_contributor_for_high_risk_assets',
       'top_country_contributor_for_productive_capacity_loss',
       'top_country_contributor_for_regional_risk',
       'top_country_contributor_for_local_critical_infrastructure',
       'clientindustryid', 'overall_productive_capacity_loss_days',
       'total_assets_count'],
      dtype='object')

In [169]:
global_risk_columns = ['entity_id', 'rcp_scenario', 'physical_impact_year',
       'data_quality_asset_damage_risk', 'data_quality_high_risk_assets',
       'data_quality_productive_capacity_loss', 'high_risk_assets_count',
       'industry_category_asset_damage_risk',
       'industry_category_high_risk_assets',
       'industry_category_productive_capacity_loss',
       'industry_percentile_asset_damage_risk',
       'industry_percentile_high_risk_assets',
       'industry_percentile_productive_capacity_loss',
       'overall_asset_damage_risk', 'overall_category_asset_damage_risk',
       'overall_category_high_risk_assets',
       'overall_high_risk_assets_percentage',
       'overall_percentile_asset_damage_risk',
       'overall_percentile_high_risk_assets',
       'overall_percentile_productive_capacity_loss',
       'overall_productive_capacity_loss',
       'overall_productive_capacity_loss_days', 'total_assets_count',
       'dt_created', 'dt_updated', 'fl_deleted', 'timestamps',
       'overall_category_productive_capacity_loss',
       'overall_percentile_regional_infrastructure_risk',
       'overall_category_regional_infrastructure_risk',
       'industry_percentile_regional_infrastructure_risk',
       'industry_category_regional_infrastructure_risk',
       'overall_percentile_local_critical_infrastructure_risk',
       'overall_category_local_critical_infrastructure_risk',
       'industry_percentile_local_critical_infrastructure_risk',
       'industry_category_local_critical_infrastructure_risk',
       'top_hazard_contributor_for_asset_damage_risk',
       'top_country_contributor_for_asset_damage_risk',
       'top_hazard_contributor_for_productive_capacity_loss',
       'top_country_contributor_for_productive_capacity_loss',
       'top_country_contributor_for_high_risk_assets',
       'top_country_contributor_for_regional_risk',
       'top_country_contributor_for_local_critical_infrastructure']
set(global_risk_columns)- set(global_semi_df.columns)

{'data_quality_asset_damage_risk',
 'data_quality_high_risk_assets',
 'data_quality_productive_capacity_loss',
 'dt_created',
 'dt_updated',
 'fl_deleted',
 'industry_category_asset_damage_risk',
 'industry_category_high_risk_assets',
 'industry_category_local_critical_infrastructure_risk',
 'industry_category_productive_capacity_loss',
 'industry_category_regional_infrastructure_risk',
 'industry_percentile_asset_damage_risk',
 'industry_percentile_high_risk_assets',
 'industry_percentile_local_critical_infrastructure_risk',
 'industry_percentile_productive_capacity_loss',
 'industry_percentile_regional_infrastructure_risk',
 'overall_category_asset_damage_risk',
 'overall_category_high_risk_assets',
 'overall_category_local_critical_infrastructure_risk',
 'overall_category_productive_capacity_loss',
 'overall_category_regional_infrastructure_risk',
 'overall_percentile_asset_damage_risk',
 'overall_percentile_high_risk_assets',
 'overall_percentile_local_critical_infrastructure_risk',
 'overall_percentile_productive_capacity_loss',
 'overall_percentile_regional_infrastructure_risk',
 'timestamps'}